// proto definition for OSP server runtime configs

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: config.proto

package rtconfig

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RuntimeConfig is the data object holding configs reloadable during runtime
// numeric field name should end with unit, eg. gwei, ms
// Next tag: 21
type RuntimeConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// wait seconds before accepting next open chan request
	// if 0, means no wait. negative values are treated as 0
	// use int64 instead of uint64 because golang time use int64
	OpenChanWaitS int64 `protobuf:"varint,1,opt,name=open_chan_wait_s,json=openChanWaitS,proto3" json:"open_chan_wait_s,omitempty"`
	// minimal gas price in gwei for onchain tx
	// 0 isn't a valid value
	MinGasGwei uint64 `protobuf:"varint,2,opt,name=min_gas_gwei,json=minGasGwei,proto3" json:"min_gas_gwei,omitempty"`
	// max gas price in gwei for onchain tx
	// if 0, means no max
	MaxGasGwei uint64 `protobuf:"varint,3,opt,name=max_gas_gwei,json=maxGasGwei,proto3" json:"max_gas_gwei,omitempty"`
	// add gas price to the suggested price to speed up transaction
	AddGasGwei uint64 `protobuf:"varint,20,opt,name=add_gas_gwei,json=addGasGwei,proto3" json:"add_gas_gwei,omitempty"`
	// wait time (in seconds) of stream send.
	StreamSendTimeoutS uint64 `protobuf:"varint,4,opt,name=stream_send_timeout_s,json=streamSendTimeoutS,proto3" json:"stream_send_timeout_s,omitempty"`
	// decimal. eth deposit cap for cold bootstrap
	EthColdBootstrapDeposit string `protobuf:"bytes,5,opt,name=eth_cold_bootstrap_deposit,json=ethColdBootstrapDeposit,proto3" json:"eth_cold_bootstrap_deposit,omitempty"`
	// key:hex without "0x", value:decimal. Per token deposit cap for cold bootstrap
	Erc20ColdBootstrapDepositMap map[string]string `protobuf:"bytes,6,rep,name=erc20_cold_bootstrap_deposit_map,json=erc20ColdBootstrapDepositMap,proto3" json:"erc20_cold_bootstrap_deposit_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// decimal. Default token deposit cap for cold bootstrap
	Erc20ColdBootstrapDepositDefault string `protobuf:"bytes,7,opt,name=erc20_cold_bootstrap_deposit_default,json=erc20ColdBootstrapDepositDefault,proto3" json:"erc20_cold_bootstrap_deposit_default,omitempty"`
	// Multiplier cap
	OspDepositMultiplier int64 `protobuf:"varint,8,opt,name=osp_deposit_multiplier,json=ospDepositMultiplier,proto3" json:"osp_deposit_multiplier,omitempty"`
	// max dispute timeout in open channel request.
	MaxDisputeTimeout uint64 `protobuf:"varint,9,opt,name=max_dispute_timeout,json=maxDisputeTimeout,proto3" json:"max_dispute_timeout,omitempty"`
	// min dispute timeout in open channel request.
	MinDisputeTimeout uint64 `protobuf:"varint,10,opt,name=min_dispute_timeout,json=minDisputeTimeout,proto3" json:"min_dispute_timeout,omitempty"`
	// log level: trace, debug, info, warn, error, fatal, panic
	LogLevel        string           `protobuf:"bytes,11,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	TcbConfigs      *TcbConfigs      `protobuf:"bytes,12,opt,name=tcb_configs,json=tcbConfigs,proto3" json:"tcb_configs,omitempty"`
	StandardConfigs *StandardConfigs `protobuf:"bytes,13,opt,name=standard_configs,json=standardConfigs,proto3" json:"standard_configs,omitempty"`
	// OspToOsp config is keyed by pair (peerOspAddr, tokenAddr)
	OspToOspOpenConfigs *OspToOspOpenConfigs `protobuf:"bytes,17,opt,name=osp_to_osp_open_configs,json=ospToOspOpenConfigs,proto3" json:"osp_to_osp_open_configs,omitempty"`
	// max payment timeout (in seconds) the OSP accepts
	MaxPaymentTimeout uint64 `protobuf:"varint,14,opt,name=max_payment_timeout,json=maxPaymentTimeout,proto3" json:"max_payment_timeout,omitempty"`
	// max number of pending pay IDs in the simplex state
	MaxNumPendingPays uint64 `protobuf:"varint,15,opt,name=max_num_pending_pays,json=maxNumPendingPays,proto3" json:"max_num_pending_pays,omitempty"`
	// channel refill configuration
	RefillConfigs *RefillConfigs `protobuf:"bytes,16,opt,name=refill_configs,json=refillConfigs,proto3" json:"refill_configs,omitempty"`
	// deposit configuration
	DepositConfig *DepositConfig `protobuf:"bytes,18,opt,name=deposit_config,json=depositConfig,proto3" json:"deposit_config,omitempty"`
	// config to wait mined tx
	WaitMinedConfig *WaitMinedConfig `protobuf:"bytes,19,opt,name=wait_mined_config,json=waitMinedConfig,proto3" json:"wait_mined_config,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuntimeConfig) Reset() {
	*x = RuntimeConfig{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeConfig) ProtoMessage() {}

func (x *RuntimeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeConfig.ProtoReflect.Descriptor instead.
func (*RuntimeConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeConfig) GetOpenChanWaitS() int64 {
	if x != nil {
		return x.OpenChanWaitS
	}
	return 0
}

func (x *RuntimeConfig) GetMinGasGwei() uint64 {
	if x != nil {
		return x.MinGasGwei
	}
	return 0
}

func (x *RuntimeConfig) GetMaxGasGwei() uint64 {
	if x != nil {
		return x.MaxGasGwei
	}
	return 0
}

func (x *RuntimeConfig) GetAddGasGwei() uint64 {
	if x != nil {
		return x.AddGasGwei
	}
	return 0
}

func (x *RuntimeConfig) GetStreamSendTimeoutS() uint64 {
	if x != nil {
		return x.StreamSendTimeoutS
	}
	return 0
}

func (x *RuntimeConfig) GetEthColdBootstrapDeposit() string {
	if x != nil {
		return x.EthColdBootstrapDeposit
	}
	return ""
}

func (x *RuntimeConfig) GetErc20ColdBootstrapDepositMap() map[string]string {
	if x != nil {
		return x.Erc20ColdBootstrapDepositMap
	}
	return nil
}

func (x *RuntimeConfig) GetErc20ColdBootstrapDepositDefault() string {
	if x != nil {
		return x.Erc20ColdBootstrapDepositDefault
	}
	return ""
}

func (x *RuntimeConfig) GetOspDepositMultiplier() int64 {
	if x != nil {
		return x.OspDepositMultiplier
	}
	return 0
}

func (x *RuntimeConfig) GetMaxDisputeTimeout() uint64 {
	if x != nil {
		return x.MaxDisputeTimeout
	}
	return 0
}

func (x *RuntimeConfig) GetMinDisputeTimeout() uint64 {
	if x != nil {
		return x.MinDisputeTimeout
	}
	return 0
}

func (x *RuntimeConfig) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *RuntimeConfig) GetTcbConfigs() *TcbConfigs {
	if x != nil {
		return x.TcbConfigs
	}
	return nil
}

func (x *RuntimeConfig) GetStandardConfigs() *StandardConfigs {
	if x != nil {
		return x.StandardConfigs
	}
	return nil
}

func (x *RuntimeConfig) GetOspToOspOpenConfigs() *OspToOspOpenConfigs {
	if x != nil {
		return x.OspToOspOpenConfigs
	}
	return nil
}

func (x *RuntimeConfig) GetMaxPaymentTimeout() uint64 {
	if x != nil {
		return x.MaxPaymentTimeout
	}
	return 0
}

func (x *RuntimeConfig) GetMaxNumPendingPays() uint64 {
	if x != nil {
		return x.MaxNumPendingPays
	}
	return 0
}

func (x *RuntimeConfig) GetRefillConfigs() *RefillConfigs {
	if x != nil {
		return x.RefillConfigs
	}
	return nil
}

func (x *RuntimeConfig) GetDepositConfig() *DepositConfig {
	if x != nil {
		return x.DepositConfig
	}
	return nil
}

func (x *RuntimeConfig) GetWaitMinedConfig() *WaitMinedConfig {
	if x != nil {
		return x.WaitMinedConfig
	}
	return nil
}

// Next Tag: 3
type Token struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErcType       string                 `protobuf:"bytes,1,opt,name=erc_type,json=ercType,proto3" json:"erc_type,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token) Reset() {
	*x = Token{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Token) GetErcType() string {
	if x != nil {
		return x.ErcType
	}
	return ""
}

func (x *Token) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Next Tag: 6
type TcbConfig struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Token                      *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MaxOspDeposit              string                 `protobuf:"bytes,2,opt,name=max_osp_deposit,json=maxOspDeposit,proto3" json:"max_osp_deposit,omitempty"`
	OnchainBalanceSafeMargin   string                 `protobuf:"bytes,3,opt,name=onchain_balance_safe_margin,json=onchainBalanceSafeMargin,proto3" json:"onchain_balance_safe_margin,omitempty"`
	RequiredSocialVerification bool                   `protobuf:"varint,4,opt,name=required_social_verification,json=requiredSocialVerification,proto3" json:"required_social_verification,omitempty"`
	SkipOverCommitCheck        bool                   `protobuf:"varint,5,opt,name=skip_over_commit_check,json=skipOverCommitCheck,proto3" json:"skip_over_commit_check,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TcbConfig) Reset() {
	*x = TcbConfig{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcbConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcbConfig) ProtoMessage() {}

func (x *TcbConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcbConfig.ProtoReflect.Descriptor instead.
func (*TcbConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *TcbConfig) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TcbConfig) GetMaxOspDeposit() string {
	if x != nil {
		return x.MaxOspDeposit
	}
	return ""
}

func (x *TcbConfig) GetOnchainBalanceSafeMargin() string {
	if x != nil {
		return x.OnchainBalanceSafeMargin
	}
	return ""
}

func (x *TcbConfig) GetRequiredSocialVerification() bool {
	if x != nil {
		return x.RequiredSocialVerification
	}
	return false
}

func (x *TcbConfig) GetSkipOverCommitCheck() bool {
	if x != nil {
		return x.SkipOverCommitCheck
	}
	return false
}

// Next Tag: 2
type TcbConfigs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]*TcbConfig  `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcbConfigs) Reset() {
	*x = TcbConfigs{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcbConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcbConfigs) ProtoMessage() {}

func (x *TcbConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcbConfigs.ProtoReflect.Descriptor instead.
func (*TcbConfigs) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *TcbConfigs) GetConfig() map[string]*TcbConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Next Tag: 7
type StandardConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Token            *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	MinDeposit       string                 `protobuf:"bytes,5,opt,name=min_deposit,json=minDeposit,proto3" json:"min_deposit,omitempty"`
	MaxDeposit       string                 `protobuf:"bytes,2,opt,name=max_deposit,json=maxDeposit,proto3" json:"max_deposit,omitempty"`
	MinDeadlineDelta uint64                 `protobuf:"varint,3,opt,name=min_deadline_delta,json=minDeadlineDelta,proto3" json:"min_deadline_delta,omitempty"`
	MaxDeadlineDelta uint64                 `protobuf:"varint,4,opt,name=max_deadline_delta,json=maxDeadlineDelta,proto3" json:"max_deadline_delta,omitempty"`
	// matching ratio of approving osp
	// deposit of approving osp / deposit of requesting osp <= matching ratio
	MatchingRatio float32 `protobuf:"fixed32,6,opt,name=matching_ratio,json=matchingRatio,proto3" json:"matching_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardConfig) Reset() {
	*x = StandardConfig{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardConfig) ProtoMessage() {}

func (x *StandardConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardConfig.ProtoReflect.Descriptor instead.
func (*StandardConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *StandardConfig) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *StandardConfig) GetMinDeposit() string {
	if x != nil {
		return x.MinDeposit
	}
	return ""
}

func (x *StandardConfig) GetMaxDeposit() string {
	if x != nil {
		return x.MaxDeposit
	}
	return ""
}

func (x *StandardConfig) GetMinDeadlineDelta() uint64 {
	if x != nil {
		return x.MinDeadlineDelta
	}
	return 0
}

func (x *StandardConfig) GetMaxDeadlineDelta() uint64 {
	if x != nil {
		return x.MaxDeadlineDelta
	}
	return 0
}

func (x *StandardConfig) GetMatchingRatio() float32 {
	if x != nil {
		return x.MatchingRatio
	}
	return 0
}

// Next Tag: 2
type StandardConfigs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// keyed by token addr.
	Config        map[string]*StandardConfig `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardConfigs) Reset() {
	*x = StandardConfigs{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardConfigs) ProtoMessage() {}

func (x *StandardConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardConfigs.ProtoReflect.Descriptor instead.
func (*StandardConfigs) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *StandardConfigs) GetConfig() map[string]*StandardConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Next Tag: 2
type OspToOspOpenConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// tokenAddr -> OneTokenOspToOspOpenConfig
	TokensConfig  map[string]*StandardConfig `protobuf:"bytes,1,rep,name=tokens_config,json=tokensConfig,proto3" json:"tokens_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspToOspOpenConfig) Reset() {
	*x = OspToOspOpenConfig{}
	mi := &file_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspToOspOpenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspToOspOpenConfig) ProtoMessage() {}

func (x *OspToOspOpenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspToOspOpenConfig.ProtoReflect.Descriptor instead.
func (*OspToOspOpenConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{6}
}

func (x *OspToOspOpenConfig) GetTokensConfig() map[string]*StandardConfig {
	if x != nil {
		return x.TokensConfig
	}
	return nil
}

// Next Tag: 2
type OspToOspOpenConfigs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ospAddr ->  OspToOspOpenConfig
	Configs       map[string]*OspToOspOpenConfig `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspToOspOpenConfigs) Reset() {
	*x = OspToOspOpenConfigs{}
	mi := &file_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspToOspOpenConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspToOspOpenConfigs) ProtoMessage() {}

func (x *OspToOspOpenConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspToOspOpenConfigs.ProtoReflect.Descriptor instead.
func (*OspToOspOpenConfigs) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{7}
}

func (x *OspToOspOpenConfigs) GetConfigs() map[string]*OspToOspOpenConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

// Next Tag: 4
type RefillConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Threshold     string                 `protobuf:"bytes,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	RefillAmount  string                 `protobuf:"bytes,3,opt,name=refill_amount,json=refillAmount,proto3" json:"refill_amount,omitempty"`
	PoolSize      string                 `protobuf:"bytes,4,opt,name=pool_size,json=poolSize,proto3" json:"pool_size,omitempty"`
	PoolLowRatio  float64                `protobuf:"fixed64,5,opt,name=pool_low_ratio,json=poolLowRatio,proto3" json:"pool_low_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefillConfig) Reset() {
	*x = RefillConfig{}
	mi := &file_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefillConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefillConfig) ProtoMessage() {}

func (x *RefillConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefillConfig.ProtoReflect.Descriptor instead.
func (*RefillConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{8}
}

func (x *RefillConfig) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RefillConfig) GetThreshold() string {
	if x != nil {
		return x.Threshold
	}
	return ""
}

func (x *RefillConfig) GetRefillAmount() string {
	if x != nil {
		return x.RefillAmount
	}
	return ""
}

func (x *RefillConfig) GetPoolSize() string {
	if x != nil {
		return x.PoolSize
	}
	return ""
}

func (x *RefillConfig) GetPoolLowRatio() float64 {
	if x != nil {
		return x.PoolLowRatio
	}
	return 0
}

// Next Tag: 3
type RefillConfigs struct {
	state  protoimpl.MessageState   `protogen:"open.v1"`
	Config map[string]*RefillConfig `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// max batch waiting time in seconds
	MaxWaitS      uint64 `protobuf:"varint,2,opt,name=max_wait_s,json=maxWaitS,proto3" json:"max_wait_s,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefillConfigs) Reset() {
	*x = RefillConfigs{}
	mi := &file_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefillConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefillConfigs) ProtoMessage() {}

func (x *RefillConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefillConfigs.ProtoReflect.Descriptor instead.
func (*RefillConfigs) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{9}
}

func (x *RefillConfigs) GetConfig() map[string]*RefillConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *RefillConfigs) GetMaxWaitS() uint64 {
	if x != nil {
		return x.MaxWaitS
	}
	return 0
}

// Next Tag: 4
type DepositConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// deposit polling interval in seconds
	PollingIntervalS uint64 `protobuf:"varint,1,opt,name=polling_interval_s,json=pollingIntervalS,proto3" json:"polling_interval_s,omitempty"`
	MinBatchSize     uint64 `protobuf:"varint,2,opt,name=min_batch_size,json=minBatchSize,proto3" json:"min_batch_size,omitempty"`
	MaxBatchSize     uint64 `protobuf:"varint,3,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DepositConfig) Reset() {
	*x = DepositConfig{}
	mi := &file_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositConfig) ProtoMessage() {}

func (x *DepositConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositConfig.ProtoReflect.Descriptor instead.
func (*DepositConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{10}
}

func (x *DepositConfig) GetPollingIntervalS() uint64 {
	if x != nil {
		return x.PollingIntervalS
	}
	return 0
}

func (x *DepositConfig) GetMinBatchSize() uint64 {
	if x != nil {
		return x.MinBatchSize
	}
	return 0
}

func (x *DepositConfig) GetMaxBatchSize() uint64 {
	if x != nil {
		return x.MaxBatchSize
	}
	return 0
}

type WaitMinedConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TxTimeoutS            uint64                 `protobuf:"varint,1,opt,name=tx_timeout_s,json=txTimeoutS,proto3" json:"tx_timeout_s,omitempty"`
	TxQueryTimeoutS       uint64                 `protobuf:"varint,2,opt,name=tx_query_timeout_s,json=txQueryTimeoutS,proto3" json:"tx_query_timeout_s,omitempty"`
	TxQueryRetryIntervalS uint64                 `protobuf:"varint,3,opt,name=tx_query_retry_interval_s,json=txQueryRetryIntervalS,proto3" json:"tx_query_retry_interval_s,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WaitMinedConfig) Reset() {
	*x = WaitMinedConfig{}
	mi := &file_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitMinedConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitMinedConfig) ProtoMessage() {}

func (x *WaitMinedConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitMinedConfig.ProtoReflect.Descriptor instead.
func (*WaitMinedConfig) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{11}
}

func (x *WaitMinedConfig) GetTxTimeoutS() uint64 {
	if x != nil {
		return x.TxTimeoutS
	}
	return 0
}

func (x *WaitMinedConfig) GetTxQueryTimeoutS() uint64 {
	if x != nil {
		return x.TxQueryTimeoutS
	}
	return 0
}

func (x *WaitMinedConfig) GetTxQueryRetryIntervalS() uint64 {
	if x != nil {
		return x.TxQueryRetryIntervalS
	}
	return 0
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\"\xa0\t\n" +
	"\rRuntimeConfig\x12'\n" +
	"\x10open_chan_wait_s\x18\x01 \x01(\x03R\ropenChanWaitS\x12 \n" +
	"\fmin_gas_gwei\x18\x02 \x01(\x04R\n" +
	"minGasGwei\x12 \n" +
	"\fmax_gas_gwei\x18\x03 \x01(\x04R\n" +
	"maxGasGwei\x12 \n" +
	"\fadd_gas_gwei\x18\x14 \x01(\x04R\n" +
	"addGasGwei\x121\n" +
	"\x15stream_send_timeout_s\x18\x04 \x01(\x04R\x12streamSendTimeoutS\x12;\n" +
	"\x1aeth_cold_bootstrap_deposit\x18\x05 \x01(\tR\x17ethColdBootstrapDeposit\x12x\n" +
	" erc20_cold_bootstrap_deposit_map\x18\x06 \x03(\v20.RuntimeConfig.Erc20ColdBootstrapDepositMapEntryR\x1cerc20ColdBootstrapDepositMap\x12N\n" +
	"$erc20_cold_bootstrap_deposit_default\x18\a \x01(\tR erc20ColdBootstrapDepositDefault\x124\n" +
	"\x16osp_deposit_multiplier\x18\b \x01(\x03R\x14ospDepositMultiplier\x12.\n" +
	"\x13max_dispute_timeout\x18\t \x01(\x04R\x11maxDisputeTimeout\x12.\n" +
	"\x13min_dispute_timeout\x18\n" +
	" \x01(\x04R\x11minDisputeTimeout\x12\x1b\n" +
	"\tlog_level\x18\v \x01(\tR\blogLevel\x12,\n" +
	"\vtcb_configs\x18\f \x01(\v2\v.TcbConfigsR\n" +
	"tcbConfigs\x12;\n" +
	"\x10standard_configs\x18\r \x01(\v2\x10.StandardConfigsR\x0fstandardConfigs\x12J\n" +
	"\x17osp_to_osp_open_configs\x18\x11 \x01(\v2\x14.OspToOspOpenConfigsR\x13ospToOspOpenConfigs\x12.\n" +
	"\x13max_payment_timeout\x18\x0e \x01(\x04R\x11maxPaymentTimeout\x12/\n" +
	"\x14max_num_pending_pays\x18\x0f \x01(\x04R\x11maxNumPendingPays\x125\n" +
	"\x0erefill_configs\x18\x10 \x01(\v2\x0e.RefillConfigsR\rrefillConfigs\x125\n" +
	"\x0edeposit_config\x18\x12 \x01(\v2\x0e.DepositConfigR\rdepositConfig\x12<\n" +
	"\x11wait_mined_config\x18\x13 \x01(\v2\x10.WaitMinedConfigR\x0fwaitMinedConfig\x1aO\n" +
	"!Erc20ColdBootstrapDepositMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x05Token\x12\x19\n" +
	"\berc_type\x18\x01 \x01(\tR\aercType\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\x87\x02\n" +
	"\tTcbConfig\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\v2\x06.TokenR\x05token\x12&\n" +
	"\x0fmax_osp_deposit\x18\x02 \x01(\tR\rmaxOspDeposit\x12=\n" +
	"\x1bonchain_balance_safe_margin\x18\x03 \x01(\tR\x18onchainBalanceSafeMargin\x12@\n" +
	"\x1crequired_social_verification\x18\x04 \x01(\bR\x1arequiredSocialVerification\x123\n" +
	"\x16skip_over_commit_check\x18\x05 \x01(\bR\x13skipOverCommitCheck\"\x84\x01\n" +
	"\n" +
	"TcbConfigs\x12/\n" +
	"\x06config\x18\x01 \x03(\v2\x17.TcbConfigs.ConfigEntryR\x06config\x1aE\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".TcbConfigR\x05value:\x028\x01\"\xf3\x01\n" +
	"\x0eStandardConfig\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\v2\x06.TokenR\x05token\x12\x1f\n" +
	"\vmin_deposit\x18\x05 \x01(\tR\n" +
	"minDeposit\x12\x1f\n" +
	"\vmax_deposit\x18\x02 \x01(\tR\n" +
	"maxDeposit\x12,\n" +
	"\x12min_deadline_delta\x18\x03 \x01(\x04R\x10minDeadlineDelta\x12,\n" +
	"\x12max_deadline_delta\x18\x04 \x01(\x04R\x10maxDeadlineDelta\x12%\n" +
	"\x0ematching_ratio\x18\x06 \x01(\x02R\rmatchingRatio\"\x93\x01\n" +
	"\x0fStandardConfigs\x124\n" +
	"\x06config\x18\x01 \x03(\v2\x1c.StandardConfigs.ConfigEntryR\x06config\x1aJ\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.StandardConfigR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x12OspToOspOpenConfig\x12J\n" +
	"\rtokens_config\x18\x01 \x03(\v2%.OspToOspOpenConfig.TokensConfigEntryR\ftokensConfig\x1aP\n" +
	"\x11TokensConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.StandardConfigR\x05value:\x028\x01\"\xa3\x01\n" +
	"\x13OspToOspOpenConfigs\x12;\n" +
	"\aconfigs\x18\x01 \x03(\v2!.OspToOspOpenConfigs.ConfigsEntryR\aconfigs\x1aO\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.OspToOspOpenConfigR\x05value:\x028\x01\"\xb2\x01\n" +
	"\fRefillConfig\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\v2\x06.TokenR\x05token\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\tR\tthreshold\x12#\n" +
	"\rrefill_amount\x18\x03 \x01(\tR\frefillAmount\x12\x1b\n" +
	"\tpool_size\x18\x04 \x01(\tR\bpoolSize\x12$\n" +
	"\x0epool_low_ratio\x18\x05 \x01(\x01R\fpoolLowRatio\"\xab\x01\n" +
	"\rRefillConfigs\x122\n" +
	"\x06config\x18\x01 \x03(\v2\x1a.RefillConfigs.ConfigEntryR\x06config\x12\x1c\n" +
	"\n" +
	"max_wait_s\x18\x02 \x01(\x04R\bmaxWaitS\x1aH\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.RefillConfigR\x05value:\x028\x01\"\x89\x01\n" +
	"\rDepositConfig\x12,\n" +
	"\x12polling_interval_s\x18\x01 \x01(\x04R\x10pollingIntervalS\x12$\n" +
	"\x0emin_batch_size\x18\x02 \x01(\x04R\fminBatchSize\x12$\n" +
	"\x0emax_batch_size\x18\x03 \x01(\x04R\fmaxBatchSize\"\x9a\x01\n" +
	"\x0fWaitMinedConfig\x12 \n" +
	"\ftx_timeout_s\x18\x01 \x01(\x04R\n" +
	"txTimeoutS\x12+\n" +
	"\x12tx_query_timeout_s\x18\x02 \x01(\x04R\x0ftxQueryTimeoutS\x128\n" +
	"\x19tx_query_retry_interval_s\x18\x03 \x01(\x04R\x15txQueryRetryIntervalSB-Z+github.com/celer-network/agent-pay/rtconfigb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_config_proto_goTypes = []any{
	(*RuntimeConfig)(nil),       // 0: RuntimeConfig
	(*Token)(nil),               // 1: Token
	(*TcbConfig)(nil),           // 2: TcbConfig
	(*TcbConfigs)(nil),          // 3: TcbConfigs
	(*StandardConfig)(nil),      // 4: StandardConfig
	(*StandardConfigs)(nil),     // 5: StandardConfigs
	(*OspToOspOpenConfig)(nil),  // 6: OspToOspOpenConfig
	(*OspToOspOpenConfigs)(nil), // 7: OspToOspOpenConfigs
	(*RefillConfig)(nil),        // 8: RefillConfig
	(*RefillConfigs)(nil),       // 9: RefillConfigs
	(*DepositConfig)(nil),       // 10: DepositConfig
	(*WaitMinedConfig)(nil),     // 11: WaitMinedConfig
	nil,                         // 12: RuntimeConfig.Erc20ColdBootstrapDepositMapEntry
	nil,                         // 13: TcbConfigs.ConfigEntry
	nil,                         // 14: StandardConfigs.ConfigEntry
	nil,                         // 15: OspToOspOpenConfig.TokensConfigEntry
	nil,                         // 16: OspToOspOpenConfigs.ConfigsEntry
	nil,                         // 17: RefillConfigs.ConfigEntry
}
var file_config_proto_depIdxs = []int32{
	12, // 0: RuntimeConfig.erc20_cold_bootstrap_deposit_map:type_name -> RuntimeConfig.Erc20ColdBootstrapDepositMapEntry
	3,  // 1: RuntimeConfig.tcb_configs:type_name -> TcbConfigs
	5,  // 2: RuntimeConfig.standard_configs:type_name -> StandardConfigs
	7,  // 3: RuntimeConfig.osp_to_osp_open_configs:type_name -> OspToOspOpenConfigs
	9,  // 4: RuntimeConfig.refill_configs:type_name -> RefillConfigs
	10, // 5: RuntimeConfig.deposit_config:type_name -> DepositConfig
	11, // 6: RuntimeConfig.wait_mined_config:type_name -> WaitMinedConfig
	1,  // 7: TcbConfig.token:type_name -> Token
	13, // 8: TcbConfigs.config:type_name -> TcbConfigs.ConfigEntry
	1,  // 9: StandardConfig.token:type_name -> Token
	14, // 10: StandardConfigs.config:type_name -> StandardConfigs.ConfigEntry
	15, // 11: OspToOspOpenConfig.tokens_config:type_name -> OspToOspOpenConfig.TokensConfigEntry
	16, // 12: OspToOspOpenConfigs.configs:type_name -> OspToOspOpenConfigs.ConfigsEntry
	1,  // 13: RefillConfig.token:type_name -> Token
	17, // 14: RefillConfigs.config:type_name -> RefillConfigs.ConfigEntry
	2,  // 15: TcbConfigs.ConfigEntry.value:type_name -> TcbConfig
	4,  // 16: StandardConfigs.ConfigEntry.value:type_name -> StandardConfig
	4,  // 17: OspToOspOpenConfig.TokensConfigEntry.value:type_name -> StandardConfig
	6,  // 18: OspToOspOpenConfigs.ConfigsEntry.value:type_name -> OspToOspOpenConfig
	8,  // 19: RefillConfigs.ConfigEntry.value:type_name -> RefillConfig
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
