// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	// ConfirmOnChainResolvedPaysWithPeerOsps instructs Osp to confirm on-chain resolved pays between itself and connected osps.
	ConfirmOnChainResolvedPaysWithPeerOsps(ctx context.Context, in *ConfirmOnChainResolvedPaysRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ClearExpiredPaysWithPeerOsps instructs Osp to clear expired pays between itself and connected osps.
	ClearExpiredPaysWithPeerOsps(ctx context.Context, in *ClearExpiredPaysRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// BuildRoutingTable instructs Osp to build routing table.
	BuildRoutingTable(ctx context.Context, in *BuildRoutingTableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RecvBcastRoutingInfo gives the OSP (listener & router) the incoming
	// broadcast routing information (OSP server forwarding to the listener).
	RecvBcastRoutingInfo(ctx context.Context, in *RoutingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetPeerOsps returns info of all peer osps.
	GetPeerOsps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PeerOspsResponse, error)
	// OspOpenChannel instructs Osp to open a state channel with a peer described in request.
	OspOpenChannel(ctx context.Context, in *OspOpenChannelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SendToken instructs the OSP to send token specified in SendTokenRequest.
	SendToken(ctx context.Context, in *SendTokenRequest, opts ...grpc.CallOption) (*SendTokenResponse, error)
	// Deposit instructs the OSP to deposit token specified in DepositRequest.
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	// QueryDeposit asks OSP about the deposit status
	QueryDeposit(ctx context.Context, in *QueryDepositRequest, opts ...grpc.CallOption) (*QueryDepositResponse, error)
	// RegisterStream instructs the OSP to connect with other osp specified in RegisterStreamRequest.
	RegisterStream(ctx context.Context, in *RegisterStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CooperativeWithdraw(ctx context.Context, in *ChannelOpRequest, opts ...grpc.CallOption) (*ChannelOpResponse, error)
	CooperativeSettle(ctx context.Context, in *ChannelOpRequest, opts ...grpc.CallOption) (*ChannelOpResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) ConfirmOnChainResolvedPaysWithPeerOsps(ctx context.Context, in *ConfirmOnChainResolvedPaysRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/ConfirmOnChainResolvedPaysWithPeerOsps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) ClearExpiredPaysWithPeerOsps(ctx context.Context, in *ClearExpiredPaysRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/ClearExpiredPaysWithPeerOsps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) BuildRoutingTable(ctx context.Context, in *BuildRoutingTableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/BuildRoutingTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RecvBcastRoutingInfo(ctx context.Context, in *RoutingRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/RecvBcastRoutingInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) GetPeerOsps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PeerOspsResponse, error) {
	out := new(PeerOspsResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/GetPeerOsps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) OspOpenChannel(ctx context.Context, in *OspOpenChannelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/OspOpenChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) SendToken(ctx context.Context, in *SendTokenRequest, opts ...grpc.CallOption) (*SendTokenResponse, error) {
	out := new(SendTokenResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/SendToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) QueryDeposit(ctx context.Context, in *QueryDepositRequest, opts ...grpc.CallOption) (*QueryDepositResponse, error) {
	out := new(QueryDepositResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/QueryDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) RegisterStream(ctx context.Context, in *RegisterStreamRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Admin/RegisterStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CooperativeWithdraw(ctx context.Context, in *ChannelOpRequest, opts ...grpc.CallOption) (*ChannelOpResponse, error) {
	out := new(ChannelOpResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/CooperativeWithdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) CooperativeSettle(ctx context.Context, in *ChannelOpRequest, opts ...grpc.CallOption) (*ChannelOpResponse, error) {
	out := new(ChannelOpResponse)
	err := c.cc.Invoke(ctx, "/rpc.Admin/CooperativeSettle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations should embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	// ConfirmOnChainResolvedPaysWithPeerOsps instructs Osp to confirm on-chain resolved pays between itself and connected osps.
	ConfirmOnChainResolvedPaysWithPeerOsps(context.Context, *ConfirmOnChainResolvedPaysRequest) (*emptypb.Empty, error)
	// ClearExpiredPaysWithPeerOsps instructs Osp to clear expired pays between itself and connected osps.
	ClearExpiredPaysWithPeerOsps(context.Context, *ClearExpiredPaysRequest) (*emptypb.Empty, error)
	// BuildRoutingTable instructs Osp to build routing table.
	BuildRoutingTable(context.Context, *BuildRoutingTableRequest) (*emptypb.Empty, error)
	// RecvBcastRoutingInfo gives the OSP (listener & router) the incoming
	// broadcast routing information (OSP server forwarding to the listener).
	RecvBcastRoutingInfo(context.Context, *RoutingRequest) (*emptypb.Empty, error)
	// GetPeerOsps returns info of all peer osps.
	GetPeerOsps(context.Context, *emptypb.Empty) (*PeerOspsResponse, error)
	// OspOpenChannel instructs Osp to open a state channel with a peer described in request.
	OspOpenChannel(context.Context, *OspOpenChannelRequest) (*emptypb.Empty, error)
	// SendToken instructs the OSP to send token specified in SendTokenRequest.
	SendToken(context.Context, *SendTokenRequest) (*SendTokenResponse, error)
	// Deposit instructs the OSP to deposit token specified in DepositRequest.
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	// QueryDeposit asks OSP about the deposit status
	QueryDeposit(context.Context, *QueryDepositRequest) (*QueryDepositResponse, error)
	// RegisterStream instructs the OSP to connect with other osp specified in RegisterStreamRequest.
	RegisterStream(context.Context, *RegisterStreamRequest) (*emptypb.Empty, error)
	CooperativeWithdraw(context.Context, *ChannelOpRequest) (*ChannelOpResponse, error)
	CooperativeSettle(context.Context, *ChannelOpRequest) (*ChannelOpResponse, error)
}

// UnimplementedAdminServer should be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) ConfirmOnChainResolvedPaysWithPeerOsps(context.Context, *ConfirmOnChainResolvedPaysRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmOnChainResolvedPaysWithPeerOsps not implemented")
}
func (UnimplementedAdminServer) ClearExpiredPaysWithPeerOsps(context.Context, *ClearExpiredPaysRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearExpiredPaysWithPeerOsps not implemented")
}
func (UnimplementedAdminServer) BuildRoutingTable(context.Context, *BuildRoutingTableRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuildRoutingTable not implemented")
}
func (UnimplementedAdminServer) RecvBcastRoutingInfo(context.Context, *RoutingRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecvBcastRoutingInfo not implemented")
}
func (UnimplementedAdminServer) GetPeerOsps(context.Context, *emptypb.Empty) (*PeerOspsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerOsps not implemented")
}
func (UnimplementedAdminServer) OspOpenChannel(context.Context, *OspOpenChannelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OspOpenChannel not implemented")
}
func (UnimplementedAdminServer) SendToken(context.Context, *SendTokenRequest) (*SendTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendToken not implemented")
}
func (UnimplementedAdminServer) Deposit(context.Context, *DepositRequest) (*DepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedAdminServer) QueryDeposit(context.Context, *QueryDepositRequest) (*QueryDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDeposit not implemented")
}
func (UnimplementedAdminServer) RegisterStream(context.Context, *RegisterStreamRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterStream not implemented")
}
func (UnimplementedAdminServer) CooperativeWithdraw(context.Context, *ChannelOpRequest) (*ChannelOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CooperativeWithdraw not implemented")
}
func (UnimplementedAdminServer) CooperativeSettle(context.Context, *ChannelOpRequest) (*ChannelOpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CooperativeSettle not implemented")
}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_ConfirmOnChainResolvedPaysWithPeerOsps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmOnChainResolvedPaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ConfirmOnChainResolvedPaysWithPeerOsps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/ConfirmOnChainResolvedPaysWithPeerOsps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ConfirmOnChainResolvedPaysWithPeerOsps(ctx, req.(*ConfirmOnChainResolvedPaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_ClearExpiredPaysWithPeerOsps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearExpiredPaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).ClearExpiredPaysWithPeerOsps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/ClearExpiredPaysWithPeerOsps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).ClearExpiredPaysWithPeerOsps(ctx, req.(*ClearExpiredPaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_BuildRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRoutingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).BuildRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/BuildRoutingTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).BuildRoutingTable(ctx, req.(*BuildRoutingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RecvBcastRoutingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RecvBcastRoutingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/RecvBcastRoutingInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RecvBcastRoutingInfo(ctx, req.(*RoutingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_GetPeerOsps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).GetPeerOsps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/GetPeerOsps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).GetPeerOsps(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_OspOpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OspOpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).OspOpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/OspOpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).OspOpenChannel(ctx, req.(*OspOpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_SendToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).SendToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/SendToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).SendToken(ctx, req.(*SendTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_QueryDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).QueryDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/QueryDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).QueryDeposit(ctx, req.(*QueryDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_RegisterStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).RegisterStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/RegisterStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).RegisterStream(ctx, req.(*RegisterStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CooperativeWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CooperativeWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/CooperativeWithdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CooperativeWithdraw(ctx, req.(*ChannelOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_CooperativeSettle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChannelOpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).CooperativeSettle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Admin/CooperativeSettle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).CooperativeSettle(ctx, req.(*ChannelOpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmOnChainResolvedPaysWithPeerOsps",
			Handler:    _Admin_ConfirmOnChainResolvedPaysWithPeerOsps_Handler,
		},
		{
			MethodName: "ClearExpiredPaysWithPeerOsps",
			Handler:    _Admin_ClearExpiredPaysWithPeerOsps_Handler,
		},
		{
			MethodName: "BuildRoutingTable",
			Handler:    _Admin_BuildRoutingTable_Handler,
		},
		{
			MethodName: "RecvBcastRoutingInfo",
			Handler:    _Admin_RecvBcastRoutingInfo_Handler,
		},
		{
			MethodName: "GetPeerOsps",
			Handler:    _Admin_GetPeerOsps_Handler,
		},
		{
			MethodName: "OspOpenChannel",
			Handler:    _Admin_OspOpenChannel_Handler,
		},
		{
			MethodName: "SendToken",
			Handler:    _Admin_SendToken_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _Admin_Deposit_Handler,
		},
		{
			MethodName: "QueryDeposit",
			Handler:    _Admin_QueryDeposit_Handler,
		},
		{
			MethodName: "RegisterStream",
			Handler:    _Admin_RegisterStream_Handler,
		},
		{
			MethodName: "CooperativeWithdraw",
			Handler:    _Admin_CooperativeWithdraw_Handler,
		},
		{
			MethodName: "CooperativeSettle",
			Handler:    _Admin_CooperativeSettle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "osp_admin.proto",
}
