// Copyright 2018-2025 Celer Network

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: rpc.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x03rpc\x1a\rmessage.proto2\xbc\x04\n" +
	"\x03Rpc\x12H\n" +
	"\rGetPayHistory\x12\x19.rpc.GetPayHistoryRequest\x1a\x1a.rpc.GetPayHistoryResponse\"\x00\x12N\n" +
	"\x0fQueryDelegation\x12\x1b.rpc.QueryDelegationRequest\x1a\x1c.rpc.QueryDelegationResponse\"\x00\x12F\n" +
	"\x11RequestDelegation\x12\x16.rpc.DelegationRequest\x1a\x17.rpc.DelegationResponse\"\x00\x12G\n" +
	"\x10CelerOpenChannel\x12\x17.rpc.OpenChannelRequest\x1a\x18.rpc.OpenChannelResponse\"\x00\x12J\n" +
	"\x13CelerOpenTcbChannel\x12\x17.rpc.OpenChannelRequest\x1a\x18.rpc.OpenChannelResponse\"\x00\x129\n" +
	"\x12CelerGetPeerStatus\x12\x10.rpc.PeerAddress\x1a\x0f.rpc.PeerStatus\"\x00\x121\n" +
	"\vCelerStream\x12\r.rpc.CelerMsg\x1a\r.rpc.CelerMsg\"\x00(\x010\x01\x12P\n" +
	"\x13CelerMigrateChannel\x12\x1a.rpc.MigrateChannelRequest\x1a\x1b.rpc.MigrateChannelResponse\"\x00B(Z&github.com/celer-network/agent-pay/rpcb\x06proto3"

var file_rpc_proto_goTypes = []any{
	(*GetPayHistoryRequest)(nil),    // 0: rpc.GetPayHistoryRequest
	(*QueryDelegationRequest)(nil),  // 1: rpc.QueryDelegationRequest
	(*DelegationRequest)(nil),       // 2: rpc.DelegationRequest
	(*OpenChannelRequest)(nil),      // 3: rpc.OpenChannelRequest
	(*PeerAddress)(nil),             // 4: rpc.PeerAddress
	(*CelerMsg)(nil),                // 5: rpc.CelerMsg
	(*MigrateChannelRequest)(nil),   // 6: rpc.MigrateChannelRequest
	(*GetPayHistoryResponse)(nil),   // 7: rpc.GetPayHistoryResponse
	(*QueryDelegationResponse)(nil), // 8: rpc.QueryDelegationResponse
	(*DelegationResponse)(nil),      // 9: rpc.DelegationResponse
	(*OpenChannelResponse)(nil),     // 10: rpc.OpenChannelResponse
	(*PeerStatus)(nil),              // 11: rpc.PeerStatus
	(*MigrateChannelResponse)(nil),  // 12: rpc.MigrateChannelResponse
}
var file_rpc_proto_depIdxs = []int32{
	0,  // 0: rpc.Rpc.GetPayHistory:input_type -> rpc.GetPayHistoryRequest
	1,  // 1: rpc.Rpc.QueryDelegation:input_type -> rpc.QueryDelegationRequest
	2,  // 2: rpc.Rpc.RequestDelegation:input_type -> rpc.DelegationRequest
	3,  // 3: rpc.Rpc.CelerOpenChannel:input_type -> rpc.OpenChannelRequest
	3,  // 4: rpc.Rpc.CelerOpenTcbChannel:input_type -> rpc.OpenChannelRequest
	4,  // 5: rpc.Rpc.CelerGetPeerStatus:input_type -> rpc.PeerAddress
	5,  // 6: rpc.Rpc.CelerStream:input_type -> rpc.CelerMsg
	6,  // 7: rpc.Rpc.CelerMigrateChannel:input_type -> rpc.MigrateChannelRequest
	7,  // 8: rpc.Rpc.GetPayHistory:output_type -> rpc.GetPayHistoryResponse
	8,  // 9: rpc.Rpc.QueryDelegation:output_type -> rpc.QueryDelegationResponse
	9,  // 10: rpc.Rpc.RequestDelegation:output_type -> rpc.DelegationResponse
	10, // 11: rpc.Rpc.CelerOpenChannel:output_type -> rpc.OpenChannelResponse
	10, // 12: rpc.Rpc.CelerOpenTcbChannel:output_type -> rpc.OpenChannelResponse
	11, // 13: rpc.Rpc.CelerGetPeerStatus:output_type -> rpc.PeerStatus
	5,  // 14: rpc.Rpc.CelerStream:output_type -> rpc.CelerMsg
	12, // 15: rpc.Rpc.CelerMigrateChannel:output_type -> rpc.MigrateChannelResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	file_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
