// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// RpcClient is the client API for Rpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcClient interface {
	GetPayHistory(ctx context.Context, in *GetPayHistoryRequest, opts ...grpc.CallOption) (*GetPayHistoryResponse, error)
	QueryDelegation(ctx context.Context, in *QueryDelegationRequest, opts ...grpc.CallOption) (*QueryDelegationResponse, error)
	RequestDelegation(ctx context.Context, in *DelegationRequest, opts ...grpc.CallOption) (*DelegationResponse, error)
	CelerOpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error)
	CelerOpenTcbChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error)
	CelerGetPeerStatus(ctx context.Context, in *PeerAddress, opts ...grpc.CallOption) (*PeerStatus, error)
	// unified offchain bidi streaming rpc and msg definition
	CelerStream(ctx context.Context, opts ...grpc.CallOption) (Rpc_CelerStreamClient, error)
	CelerMigrateChannel(ctx context.Context, in *MigrateChannelRequest, opts ...grpc.CallOption) (*MigrateChannelResponse, error)
}

type rpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcClient(cc grpc.ClientConnInterface) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) GetPayHistory(ctx context.Context, in *GetPayHistoryRequest, opts ...grpc.CallOption) (*GetPayHistoryResponse, error) {
	out := new(GetPayHistoryResponse)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/GetPayHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) QueryDelegation(ctx context.Context, in *QueryDelegationRequest, opts ...grpc.CallOption) (*QueryDelegationResponse, error) {
	out := new(QueryDelegationResponse)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/QueryDelegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) RequestDelegation(ctx context.Context, in *DelegationRequest, opts ...grpc.CallOption) (*DelegationResponse, error) {
	out := new(DelegationResponse)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/RequestDelegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) CelerOpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error) {
	out := new(OpenChannelResponse)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/CelerOpenChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) CelerOpenTcbChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelResponse, error) {
	out := new(OpenChannelResponse)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/CelerOpenTcbChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) CelerGetPeerStatus(ctx context.Context, in *PeerAddress, opts ...grpc.CallOption) (*PeerStatus, error) {
	out := new(PeerStatus)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/CelerGetPeerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcClient) CelerStream(ctx context.Context, opts ...grpc.CallOption) (Rpc_CelerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Rpc_serviceDesc.Streams[0], "/rpc.Rpc/CelerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &rpcCelerStreamClient{stream}
	return x, nil
}

type Rpc_CelerStreamClient interface {
	Send(*CelerMsg) error
	Recv() (*CelerMsg, error)
	grpc.ClientStream
}

type rpcCelerStreamClient struct {
	grpc.ClientStream
}

func (x *rpcCelerStreamClient) Send(m *CelerMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *rpcCelerStreamClient) Recv() (*CelerMsg, error) {
	m := new(CelerMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *rpcClient) CelerMigrateChannel(ctx context.Context, in *MigrateChannelRequest, opts ...grpc.CallOption) (*MigrateChannelResponse, error) {
	out := new(MigrateChannelResponse)
	err := c.cc.Invoke(ctx, "/rpc.Rpc/CelerMigrateChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServer is the server API for Rpc service.
// All implementations must embed UnimplementedRpcServer
// for forward compatibility
type RpcServer interface {
	GetPayHistory(context.Context, *GetPayHistoryRequest) (*GetPayHistoryResponse, error)
	QueryDelegation(context.Context, *QueryDelegationRequest) (*QueryDelegationResponse, error)
	RequestDelegation(context.Context, *DelegationRequest) (*DelegationResponse, error)
	CelerOpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error)
	CelerOpenTcbChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error)
	CelerGetPeerStatus(context.Context, *PeerAddress) (*PeerStatus, error)
	// unified offchain bidi streaming rpc and msg definition
	CelerStream(Rpc_CelerStreamServer) error
	CelerMigrateChannel(context.Context, *MigrateChannelRequest) (*MigrateChannelResponse, error)
	mustEmbedUnimplementedRpcServer()
}

// UnimplementedRpcServer must be embedded to have forward compatible implementations.
type UnimplementedRpcServer struct {
}

func (UnimplementedRpcServer) GetPayHistory(context.Context, *GetPayHistoryRequest) (*GetPayHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPayHistory not implemented")
}
func (UnimplementedRpcServer) QueryDelegation(context.Context, *QueryDelegationRequest) (*QueryDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryDelegation not implemented")
}
func (UnimplementedRpcServer) RequestDelegation(context.Context, *DelegationRequest) (*DelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDelegation not implemented")
}
func (UnimplementedRpcServer) CelerOpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CelerOpenChannel not implemented")
}
func (UnimplementedRpcServer) CelerOpenTcbChannel(context.Context, *OpenChannelRequest) (*OpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CelerOpenTcbChannel not implemented")
}
func (UnimplementedRpcServer) CelerGetPeerStatus(context.Context, *PeerAddress) (*PeerStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CelerGetPeerStatus not implemented")
}
func (UnimplementedRpcServer) CelerStream(Rpc_CelerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CelerStream not implemented")
}
func (UnimplementedRpcServer) CelerMigrateChannel(context.Context, *MigrateChannelRequest) (*MigrateChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CelerMigrateChannel not implemented")
}
func (UnimplementedRpcServer) mustEmbedUnimplementedRpcServer() {}

// UnsafeRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServer will
// result in compilation errors.
type UnsafeRpcServer interface {
	mustEmbedUnimplementedRpcServer()
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_GetPayHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).GetPayHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/GetPayHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).GetPayHistory(ctx, req.(*GetPayHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_QueryDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).QueryDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/QueryDelegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).QueryDelegation(ctx, req.(*QueryDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_RequestDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).RequestDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/RequestDelegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).RequestDelegation(ctx, req.(*DelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_CelerOpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).CelerOpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/CelerOpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).CelerOpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_CelerOpenTcbChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).CelerOpenTcbChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/CelerOpenTcbChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).CelerOpenTcbChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_CelerGetPeerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).CelerGetPeerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/CelerGetPeerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).CelerGetPeerStatus(ctx, req.(*PeerAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rpc_CelerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RpcServer).CelerStream(&rpcCelerStreamServer{stream})
}

type Rpc_CelerStreamServer interface {
	Send(*CelerMsg) error
	Recv() (*CelerMsg, error)
	grpc.ServerStream
}

type rpcCelerStreamServer struct {
	grpc.ServerStream
}

func (x *rpcCelerStreamServer) Send(m *CelerMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *rpcCelerStreamServer) Recv() (*CelerMsg, error) {
	m := new(CelerMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Rpc_CelerMigrateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).CelerMigrateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Rpc/CelerMigrateChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).CelerMigrateChannel(ctx, req.(*MigrateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayHistory",
			Handler:    _Rpc_GetPayHistory_Handler,
		},
		{
			MethodName: "QueryDelegation",
			Handler:    _Rpc_QueryDelegation_Handler,
		},
		{
			MethodName: "RequestDelegation",
			Handler:    _Rpc_RequestDelegation_Handler,
		},
		{
			MethodName: "CelerOpenChannel",
			Handler:    _Rpc_CelerOpenChannel_Handler,
		},
		{
			MethodName: "CelerOpenTcbChannel",
			Handler:    _Rpc_CelerOpenTcbChannel_Handler,
		},
		{
			MethodName: "CelerGetPeerStatus",
			Handler:    _Rpc_CelerGetPeerStatus_Handler,
		},
		{
			MethodName: "CelerMigrateChannel",
			Handler:    _Rpc_CelerMigrateChannel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CelerStream",
			Handler:       _Rpc_CelerStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
