// Regenerated by tools/scripts/regenerate-go-bindings.sh — DO NOT EDIT.
// Code generated - DO NOT EDIT.
// This file is a generated binding and any manual changes will be lost.

package testapp

import (
	"errors"
	"math/big"
	"strings"

	ethereum "github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"github.com/ethereum/go-ethereum/event"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = errors.New
	_ = big.NewInt
	_ = strings.NewReader
	_ = ethereum.NotFound
	_ = bind.Bind
	_ = common.Big1
	_ = types.BloomLookup
	_ = event.NewSubscription
	_ = abi.ConvertType
)

// BooleanCondMockMetaData contains all meta data concerning the BooleanCondMock contract.
var BooleanCondMockMetaData = &bind.MetaData{
	ABI: "[{\"type\":\"function\",\"name\":\"getOutcome\",\"inputs\":[{\"name\":\"_query\",\"type\":\"bytes\",\"internalType\":\"bytes\"}],\"outputs\":[{\"name\":\"\",\"type\":\"bool\",\"internalType\":\"bool\"}],\"stateMutability\":\"pure\"},{\"type\":\"function\",\"name\":\"isFinalized\",\"inputs\":[{\"name\":\"_query\",\"type\":\"bytes\",\"internalType\":\"bytes\"}],\"outputs\":[{\"name\":\"\",\"type\":\"bool\",\"internalType\":\"bool\"}],\"stateMutability\":\"pure\"}]",
	Bin: "0x6080604052348015600e575f5ffd5b506102228061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063bcdbda9414610038578063ea4ba8eb1461005f575b5f5ffd5b61004b610046366004610140565b610072565b604051901515815260200160405180910390f35b61004b61006d366004610140565b6100c9565b5f818103610082575060016100c3565b6100c083838080601f0160208091040260200160405190810160405280939291908181526020018383808284375f9201919091525061010892505050565b90505b92915050565b5f6100c083838080601f0160208091040260200160405190810160405280939291908181526020018383808284375f9201919091525061010892505050565b5f81515f0361011857505f919050565b6020828101518351909161012c91906101c2565b6101379060086101d5565b1c151592915050565b5f5f60208385031215610151575f5ffd5b823567ffffffffffffffff811115610167575f5ffd5b8301601f81018513610177575f5ffd5b803567ffffffffffffffff81111561018d575f5ffd5b85602082840101111561019e575f5ffd5b6020919091019590945092505050565b634e487b7160e01b5f52601160045260245ffd5b818103818111156100c3576100c36101ae565b80820281158282048414176100c3576100c36101ae56fea2646970667358221220c12eebfbdbfdf6caab643570ac750da3584d021123904390dd66e5245cb3823f64736f6c634300081e0033",
}

// BooleanCondMockABI is the input ABI used to generate the binding from.
// Deprecated: Use BooleanCondMockMetaData.ABI instead.
var BooleanCondMockABI = BooleanCondMockMetaData.ABI

// BooleanCondMockBin is the compiled bytecode used for deploying new contracts.
// Deprecated: Use BooleanCondMockMetaData.Bin instead.
var BooleanCondMockBin = BooleanCondMockMetaData.Bin

// DeployBooleanCondMock deploys a new Ethereum contract, binding an instance of BooleanCondMock to it.
func DeployBooleanCondMock(auth *bind.TransactOpts, backend bind.ContractBackend) (common.Address, *types.Transaction, *BooleanCondMock, error) {
	parsed, err := BooleanCondMockMetaData.GetAbi()
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	if parsed == nil {
		return common.Address{}, nil, nil, errors.New("GetABI returned nil")
	}

	address, tx, contract, err := bind.DeployContract(auth, *parsed, common.FromHex(BooleanCondMockBin), backend)
	if err != nil {
		return common.Address{}, nil, nil, err
	}
	return address, tx, &BooleanCondMock{BooleanCondMockCaller: BooleanCondMockCaller{contract: contract}, BooleanCondMockTransactor: BooleanCondMockTransactor{contract: contract}, BooleanCondMockFilterer: BooleanCondMockFilterer{contract: contract}}, nil
}

// BooleanCondMock is an auto generated Go binding around an Ethereum contract.
type BooleanCondMock struct {
	BooleanCondMockCaller     // Read-only binding to the contract
	BooleanCondMockTransactor // Write-only binding to the contract
	BooleanCondMockFilterer   // Log filterer for contract events
}

// BooleanCondMockCaller is an auto generated read-only Go binding around an Ethereum contract.
type BooleanCondMockCaller struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// BooleanCondMockTransactor is an auto generated write-only Go binding around an Ethereum contract.
type BooleanCondMockTransactor struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// BooleanCondMockFilterer is an auto generated log filtering Go binding around an Ethereum contract events.
type BooleanCondMockFilterer struct {
	contract *bind.BoundContract // Generic contract wrapper for the low level calls
}

// BooleanCondMockSession is an auto generated Go binding around an Ethereum contract,
// with pre-set call and transact options.
type BooleanCondMockSession struct {
	Contract     *BooleanCondMock  // Generic contract binding to set the session for
	CallOpts     bind.CallOpts     // Call options to use throughout this session
	TransactOpts bind.TransactOpts // Transaction auth options to use throughout this session
}

// BooleanCondMockCallerSession is an auto generated read-only Go binding around an Ethereum contract,
// with pre-set call options.
type BooleanCondMockCallerSession struct {
	Contract *BooleanCondMockCaller // Generic contract caller binding to set the session for
	CallOpts bind.CallOpts          // Call options to use throughout this session
}

// BooleanCondMockTransactorSession is an auto generated write-only Go binding around an Ethereum contract,
// with pre-set transact options.
type BooleanCondMockTransactorSession struct {
	Contract     *BooleanCondMockTransactor // Generic contract transactor binding to set the session for
	TransactOpts bind.TransactOpts          // Transaction auth options to use throughout this session
}

// BooleanCondMockRaw is an auto generated low-level Go binding around an Ethereum contract.
type BooleanCondMockRaw struct {
	Contract *BooleanCondMock // Generic contract binding to access the raw methods on
}

// BooleanCondMockCallerRaw is an auto generated low-level read-only Go binding around an Ethereum contract.
type BooleanCondMockCallerRaw struct {
	Contract *BooleanCondMockCaller // Generic read-only contract binding to access the raw methods on
}

// BooleanCondMockTransactorRaw is an auto generated low-level write-only Go binding around an Ethereum contract.
type BooleanCondMockTransactorRaw struct {
	Contract *BooleanCondMockTransactor // Generic write-only contract binding to access the raw methods on
}

// NewBooleanCondMock creates a new instance of BooleanCondMock, bound to a specific deployed contract.
func NewBooleanCondMock(address common.Address, backend bind.ContractBackend) (*BooleanCondMock, error) {
	contract, err := bindBooleanCondMock(address, backend, backend, backend)
	if err != nil {
		return nil, err
	}
	return &BooleanCondMock{BooleanCondMockCaller: BooleanCondMockCaller{contract: contract}, BooleanCondMockTransactor: BooleanCondMockTransactor{contract: contract}, BooleanCondMockFilterer: BooleanCondMockFilterer{contract: contract}}, nil
}

// NewBooleanCondMockCaller creates a new read-only instance of BooleanCondMock, bound to a specific deployed contract.
func NewBooleanCondMockCaller(address common.Address, caller bind.ContractCaller) (*BooleanCondMockCaller, error) {
	contract, err := bindBooleanCondMock(address, caller, nil, nil)
	if err != nil {
		return nil, err
	}
	return &BooleanCondMockCaller{contract: contract}, nil
}

// NewBooleanCondMockTransactor creates a new write-only instance of BooleanCondMock, bound to a specific deployed contract.
func NewBooleanCondMockTransactor(address common.Address, transactor bind.ContractTransactor) (*BooleanCondMockTransactor, error) {
	contract, err := bindBooleanCondMock(address, nil, transactor, nil)
	if err != nil {
		return nil, err
	}
	return &BooleanCondMockTransactor{contract: contract}, nil
}

// NewBooleanCondMockFilterer creates a new log filterer instance of BooleanCondMock, bound to a specific deployed contract.
func NewBooleanCondMockFilterer(address common.Address, filterer bind.ContractFilterer) (*BooleanCondMockFilterer, error) {
	contract, err := bindBooleanCondMock(address, nil, nil, filterer)
	if err != nil {
		return nil, err
	}
	return &BooleanCondMockFilterer{contract: contract}, nil
}

// bindBooleanCondMock binds a generic wrapper to an already deployed contract.
func bindBooleanCondMock(address common.Address, caller bind.ContractCaller, transactor bind.ContractTransactor, filterer bind.ContractFilterer) (*bind.BoundContract, error) {
	parsed, err := BooleanCondMockMetaData.GetAbi()
	if err != nil {
		return nil, err
	}
	return bind.NewBoundContract(address, *parsed, caller, transactor, filterer), nil
}

// Call invokes the (constant) contract method with params as input values and
// sets the output to result. The result type might be a single field for simple
// returns, a slice of interfaces for anonymous returns and a struct for named
// returns.
func (_BooleanCondMock *BooleanCondMockRaw) Call(opts *bind.CallOpts, result *[]interface{}, method string, params ...interface{}) error {
	return _BooleanCondMock.Contract.BooleanCondMockCaller.contract.Call(opts, result, method, params...)
}

// Transfer initiates a plain transaction to move funds to the contract, calling
// its default method if one is available.
func (_BooleanCondMock *BooleanCondMockRaw) Transfer(opts *bind.TransactOpts) (*types.Transaction, error) {
	return _BooleanCondMock.Contract.BooleanCondMockTransactor.contract.Transfer(opts)
}

// Transact invokes the (paid) contract method with params as input values.
func (_BooleanCondMock *BooleanCondMockRaw) Transact(opts *bind.TransactOpts, method string, params ...interface{}) (*types.Transaction, error) {
	return _BooleanCondMock.Contract.BooleanCondMockTransactor.contract.Transact(opts, method, params...)
}

// Call invokes the (constant) contract method with params as input values and
// sets the output to result. The result type might be a single field for simple
// returns, a slice of interfaces for anonymous returns and a struct for named
// returns.
func (_BooleanCondMock *BooleanCondMockCallerRaw) Call(opts *bind.CallOpts, result *[]interface{}, method string, params ...interface{}) error {
	return _BooleanCondMock.Contract.contract.Call(opts, result, method, params...)
}

// Transfer initiates a plain transaction to move funds to the contract, calling
// its default method if one is available.
func (_BooleanCondMock *BooleanCondMockTransactorRaw) Transfer(opts *bind.TransactOpts) (*types.Transaction, error) {
	return _BooleanCondMock.Contract.contract.Transfer(opts)
}

// Transact invokes the (paid) contract method with params as input values.
func (_BooleanCondMock *BooleanCondMockTransactorRaw) Transact(opts *bind.TransactOpts, method string, params ...interface{}) (*types.Transaction, error) {
	return _BooleanCondMock.Contract.contract.Transact(opts, method, params...)
}

// GetOutcome is a free data retrieval call binding the contract method 0xea4ba8eb.
//
// Solidity: function getOutcome(bytes _query) pure returns(bool)
func (_BooleanCondMock *BooleanCondMockCaller) GetOutcome(opts *bind.CallOpts, _query []byte) (bool, error) {
	var out []interface{}
	err := _BooleanCondMock.contract.Call(opts, &out, "getOutcome", _query)

	if err != nil {
		return *new(bool), err
	}

	out0 := *abi.ConvertType(out[0], new(bool)).(*bool)

	return out0, err

}

// GetOutcome is a free data retrieval call binding the contract method 0xea4ba8eb.
//
// Solidity: function getOutcome(bytes _query) pure returns(bool)
func (_BooleanCondMock *BooleanCondMockSession) GetOutcome(_query []byte) (bool, error) {
	return _BooleanCondMock.Contract.GetOutcome(&_BooleanCondMock.CallOpts, _query)
}

// GetOutcome is a free data retrieval call binding the contract method 0xea4ba8eb.
//
// Solidity: function getOutcome(bytes _query) pure returns(bool)
func (_BooleanCondMock *BooleanCondMockCallerSession) GetOutcome(_query []byte) (bool, error) {
	return _BooleanCondMock.Contract.GetOutcome(&_BooleanCondMock.CallOpts, _query)
}

// IsFinalized is a free data retrieval call binding the contract method 0xbcdbda94.
//
// Solidity: function isFinalized(bytes _query) pure returns(bool)
func (_BooleanCondMock *BooleanCondMockCaller) IsFinalized(opts *bind.CallOpts, _query []byte) (bool, error) {
	var out []interface{}
	err := _BooleanCondMock.contract.Call(opts, &out, "isFinalized", _query)

	if err != nil {
		return *new(bool), err
	}

	out0 := *abi.ConvertType(out[0], new(bool)).(*bool)

	return out0, err

}

// IsFinalized is a free data retrieval call binding the contract method 0xbcdbda94.
//
// Solidity: function isFinalized(bytes _query) pure returns(bool)
func (_BooleanCondMock *BooleanCondMockSession) IsFinalized(_query []byte) (bool, error) {
	return _BooleanCondMock.Contract.IsFinalized(&_BooleanCondMock.CallOpts, _query)
}

// IsFinalized is a free data retrieval call binding the contract method 0xbcdbda94.
//
// Solidity: function isFinalized(bytes _query) pure returns(bool)
func (_BooleanCondMock *BooleanCondMockCallerSession) IsFinalized(_query []byte) (bool, error) {
	return _BooleanCondMock.Contract.IsFinalized(&_BooleanCondMock.CallOpts, _query)
}
