// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: ocem.proto

package pem

import (
	entity "github.com/celer-network/agent-pay/entity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next tag: 17
type OpenChannelEventType int32

const (
	OpenChannelEventType_UNDEFINED_OPEN_CHANNEL_EVENT_TYPE OpenChannelEventType = 0
	OpenChannelEventType_OPEN_CHANNEL_REQUEST              OpenChannelEventType = 1
	OpenChannelEventType_OPEN_CHANNEL_API                  OpenChannelEventType = 2
	OpenChannelEventType_CHANNEL_MINED                     OpenChannelEventType = 3
	OpenChannelEventType_TCB_REQUEST                       OpenChannelEventType = 4
	OpenChannelEventType_TCB_API                           OpenChannelEventType = 5
)

// Enum value maps for OpenChannelEventType.
var (
	OpenChannelEventType_name = map[int32]string{
		0: "UNDEFINED_OPEN_CHANNEL_EVENT_TYPE",
		1: "OPEN_CHANNEL_REQUEST",
		2: "OPEN_CHANNEL_API",
		3: "CHANNEL_MINED",
		4: "TCB_REQUEST",
		5: "TCB_API",
	}
	OpenChannelEventType_value = map[string]int32{
		"UNDEFINED_OPEN_CHANNEL_EVENT_TYPE": 0,
		"OPEN_CHANNEL_REQUEST":              1,
		"OPEN_CHANNEL_API":                  2,
		"CHANNEL_MINED":                     3,
		"TCB_REQUEST":                       4,
		"TCB_API":                           5,
	}
)

func (x OpenChannelEventType) Enum() *OpenChannelEventType {
	p := new(OpenChannelEventType)
	*p = x
	return p
}

func (x OpenChannelEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpenChannelEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_ocem_proto_enumTypes[0].Descriptor()
}

func (OpenChannelEventType) Type() protoreflect.EnumType {
	return &file_ocem_proto_enumTypes[0]
}

func (x OpenChannelEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpenChannelEventType.Descriptor instead.
func (OpenChannelEventType) EnumDescriptor() ([]byte, []int) {
	return file_ocem_proto_rawDescGZIP(), []int{0}
}

// Next tag: 13
type OpenChannelEventMessage struct {
	state               protoimpl.MessageState            `protogen:"open.v1"`
	Type                OpenChannelEventType              `protobuf:"varint,1,opt,name=type,proto3,enum=pem.OpenChannelEventType" json:"type,omitempty"`
	Machine             string                            `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	StartTimeStamp      int64                             `protobuf:"varint,3,opt,name=start_time_stamp,json=startTimeStamp,proto3" json:"start_time_stamp,omitempty"`
	EndTimeStamp        int64                             `protobuf:"varint,4,opt,name=end_time_stamp,json=endTimeStamp,proto3" json:"end_time_stamp,omitempty"`
	Peer                string                            `protobuf:"bytes,5,opt,name=peer,proto3" json:"peer,omitempty"`
	Error               []string                          `protobuf:"bytes,6,rep,name=error,proto3" json:"error,omitempty"`
	TokenAddr           string                            `protobuf:"bytes,7,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	Cid                 string                            `protobuf:"bytes,8,opt,name=cid,proto3" json:"cid,omitempty"`
	ExecutionTimeMs     float32                           `protobuf:"fixed32,9,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	OspToOsp            bool                              `protobuf:"varint,10,opt,name=osp_to_osp,json=ospToOsp,proto3" json:"osp_to_osp,omitempty"`
	ReadableInitializer string                            `protobuf:"bytes,11,opt,name=readable_initializer,json=readableInitializer,proto3" json:"readable_initializer,omitempty"`
	Initializer         *entity.PaymentChannelInitializer `protobuf:"bytes,12,opt,name=initializer,proto3" json:"initializer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OpenChannelEventMessage) Reset() {
	*x = OpenChannelEventMessage{}
	mi := &file_ocem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenChannelEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenChannelEventMessage) ProtoMessage() {}

func (x *OpenChannelEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ocem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenChannelEventMessage.ProtoReflect.Descriptor instead.
func (*OpenChannelEventMessage) Descriptor() ([]byte, []int) {
	return file_ocem_proto_rawDescGZIP(), []int{0}
}

func (x *OpenChannelEventMessage) GetType() OpenChannelEventType {
	if x != nil {
		return x.Type
	}
	return OpenChannelEventType_UNDEFINED_OPEN_CHANNEL_EVENT_TYPE
}

func (x *OpenChannelEventMessage) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *OpenChannelEventMessage) GetStartTimeStamp() int64 {
	if x != nil {
		return x.StartTimeStamp
	}
	return 0
}

func (x *OpenChannelEventMessage) GetEndTimeStamp() int64 {
	if x != nil {
		return x.EndTimeStamp
	}
	return 0
}

func (x *OpenChannelEventMessage) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *OpenChannelEventMessage) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *OpenChannelEventMessage) GetTokenAddr() string {
	if x != nil {
		return x.TokenAddr
	}
	return ""
}

func (x *OpenChannelEventMessage) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *OpenChannelEventMessage) GetExecutionTimeMs() float32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *OpenChannelEventMessage) GetOspToOsp() bool {
	if x != nil {
		return x.OspToOsp
	}
	return false
}

func (x *OpenChannelEventMessage) GetReadableInitializer() string {
	if x != nil {
		return x.ReadableInitializer
	}
	return ""
}

func (x *OpenChannelEventMessage) GetInitializer() *entity.PaymentChannelInitializer {
	if x != nil {
		return x.Initializer
	}
	return nil
}

var File_ocem_proto protoreflect.FileDescriptor

const file_ocem_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ocem.proto\x12\x03pem\x1a\fentity.proto\"\xcf\x03\n" +
	"\x17OpenChannelEventMessage\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.pem.OpenChannelEventTypeR\x04type\x12\x18\n" +
	"\amachine\x18\x02 \x01(\tR\amachine\x12(\n" +
	"\x10start_time_stamp\x18\x03 \x01(\x03R\x0estartTimeStamp\x12$\n" +
	"\x0eend_time_stamp\x18\x04 \x01(\x03R\fendTimeStamp\x12\x12\n" +
	"\x04peer\x18\x05 \x01(\tR\x04peer\x12\x14\n" +
	"\x05error\x18\x06 \x03(\tR\x05error\x12\x1d\n" +
	"\n" +
	"token_addr\x18\a \x01(\tR\ttokenAddr\x12\x10\n" +
	"\x03cid\x18\b \x01(\tR\x03cid\x12*\n" +
	"\x11execution_time_ms\x18\t \x01(\x02R\x0fexecutionTimeMs\x12\x1c\n" +
	"\n" +
	"osp_to_osp\x18\n" +
	" \x01(\bR\bospToOsp\x121\n" +
	"\x14readable_initializer\x18\v \x01(\tR\x13readableInitializer\x12C\n" +
	"\vinitializer\x18\f \x01(\v2!.entity.PaymentChannelInitializerR\vinitializer*\x9e\x01\n" +
	"\x14OpenChannelEventType\x12%\n" +
	"!UNDEFINED_OPEN_CHANNEL_EVENT_TYPE\x10\x00\x12\x18\n" +
	"\x14OPEN_CHANNEL_REQUEST\x10\x01\x12\x14\n" +
	"\x10OPEN_CHANNEL_API\x10\x02\x12\x11\n" +
	"\rCHANNEL_MINED\x10\x03\x12\x0f\n" +
	"\vTCB_REQUEST\x10\x04\x12\v\n" +
	"\aTCB_API\x10\x05B(Z&github.com/celer-network/agent-pay/pemb\x06proto3"

var (
	file_ocem_proto_rawDescOnce sync.Once
	file_ocem_proto_rawDescData []byte
)

func file_ocem_proto_rawDescGZIP() []byte {
	file_ocem_proto_rawDescOnce.Do(func() {
		file_ocem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocem_proto_rawDesc), len(file_ocem_proto_rawDesc)))
	})
	return file_ocem_proto_rawDescData
}

var file_ocem_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocem_proto_goTypes = []any{
	(OpenChannelEventType)(0),                // 0: pem.OpenChannelEventType
	(*OpenChannelEventMessage)(nil),          // 1: pem.OpenChannelEventMessage
	(*entity.PaymentChannelInitializer)(nil), // 2: entity.PaymentChannelInitializer
}
var file_ocem_proto_depIdxs = []int32{
	0, // 0: pem.OpenChannelEventMessage.type:type_name -> pem.OpenChannelEventType
	2, // 1: pem.OpenChannelEventMessage.initializer:type_name -> entity.PaymentChannelInitializer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ocem_proto_init() }
func file_ocem_proto_init() {
	if File_ocem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocem_proto_rawDesc), len(file_ocem_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocem_proto_goTypes,
		DependencyIndexes: file_ocem_proto_depIdxs,
		EnumInfos:         file_ocem_proto_enumTypes,
		MessageInfos:      file_ocem_proto_msgTypes,
	}.Build()
	File_ocem_proto = out.File
	file_ocem_proto_goTypes = nil
	file_ocem_proto_depIdxs = nil
}
