// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: pem.proto

package pem

import (
	rpc "github.com/celer-network/agent-pay/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next tag: 19
type PayMessageType int32

const (
	PayMessageType_UNDEFINED_TYPE                   PayMessageType = 0
	PayMessageType_COND_PAY_REQUEST                 PayMessageType = 1
	PayMessageType_COND_PAY_RESPONSE                PayMessageType = 2
	PayMessageType_COND_PAY_RECEIPT                 PayMessageType = 3
	PayMessageType_REVEAL_SECRET                    PayMessageType = 4
	PayMessageType_REVEAL_SECRET_ACK                PayMessageType = 5
	PayMessageType_PAY_SETTLE_PROOF                 PayMessageType = 6
	PayMessageType_PAY_SETTLE_REQUEST               PayMessageType = 7
	PayMessageType_PAY_SETTLE_RESPONSE              PayMessageType = 8
	PayMessageType_SEND_TOKEN_API                   PayMessageType = 9
	PayMessageType_SRC_SETTLE_EXPIRED_PAY_API       PayMessageType = 10
	PayMessageType_DST_SETTLE_EXPIRED_PAY_API       PayMessageType = 11
	PayMessageType_CONFIRM_ON_CHAIN_PAY_API         PayMessageType = 12
	PayMessageType_REJECT_BOOLEAN_PAY_API           PayMessageType = 13
	PayMessageType_SETTLE_ON_CHAIN_RESOLVED_PAY_API PayMessageType = 14
	PayMessageType_WITHDRAW_REQUEST                 PayMessageType = 15
	PayMessageType_WITHDRAW_RESPONSE                PayMessageType = 16
	PayMessageType_CONFIRM_BOOLEAN_PAY_API          PayMessageType = 17
	PayMessageType_ROUTING_REQUEST                  PayMessageType = 18
)

// Enum value maps for PayMessageType.
var (
	PayMessageType_name = map[int32]string{
		0:  "UNDEFINED_TYPE",
		1:  "COND_PAY_REQUEST",
		2:  "COND_PAY_RESPONSE",
		3:  "COND_PAY_RECEIPT",
		4:  "REVEAL_SECRET",
		5:  "REVEAL_SECRET_ACK",
		6:  "PAY_SETTLE_PROOF",
		7:  "PAY_SETTLE_REQUEST",
		8:  "PAY_SETTLE_RESPONSE",
		9:  "SEND_TOKEN_API",
		10: "SRC_SETTLE_EXPIRED_PAY_API",
		11: "DST_SETTLE_EXPIRED_PAY_API",
		12: "CONFIRM_ON_CHAIN_PAY_API",
		13: "REJECT_BOOLEAN_PAY_API",
		14: "SETTLE_ON_CHAIN_RESOLVED_PAY_API",
		15: "WITHDRAW_REQUEST",
		16: "WITHDRAW_RESPONSE",
		17: "CONFIRM_BOOLEAN_PAY_API",
		18: "ROUTING_REQUEST",
	}
	PayMessageType_value = map[string]int32{
		"UNDEFINED_TYPE":                   0,
		"COND_PAY_REQUEST":                 1,
		"COND_PAY_RESPONSE":                2,
		"COND_PAY_RECEIPT":                 3,
		"REVEAL_SECRET":                    4,
		"REVEAL_SECRET_ACK":                5,
		"PAY_SETTLE_PROOF":                 6,
		"PAY_SETTLE_REQUEST":               7,
		"PAY_SETTLE_RESPONSE":              8,
		"SEND_TOKEN_API":                   9,
		"SRC_SETTLE_EXPIRED_PAY_API":       10,
		"DST_SETTLE_EXPIRED_PAY_API":       11,
		"CONFIRM_ON_CHAIN_PAY_API":         12,
		"REJECT_BOOLEAN_PAY_API":           13,
		"SETTLE_ON_CHAIN_RESOLVED_PAY_API": 14,
		"WITHDRAW_REQUEST":                 15,
		"WITHDRAW_RESPONSE":                16,
		"CONFIRM_BOOLEAN_PAY_API":          17,
		"ROUTING_REQUEST":                  18,
	}
)

func (x PayMessageType) Enum() *PayMessageType {
	p := new(PayMessageType)
	*p = x
	return p
}

func (x PayMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_pem_proto_enumTypes[0].Descriptor()
}

func (PayMessageType) Type() protoreflect.EnumType {
	return &file_pem_proto_enumTypes[0]
}

func (x PayMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayMessageType.Descriptor instead.
func (PayMessageType) EnumDescriptor() ([]byte, []int) {
	return file_pem_proto_rawDescGZIP(), []int{0}
}

type CrossNetPayState int32

const (
	CrossNetPayState_XNET_NULL    CrossNetPayState = 0
	CrossNetPayState_XNET_SRC     CrossNetPayState = 1
	CrossNetPayState_XNET_DST     CrossNetPayState = 2
	CrossNetPayState_XNET_INGRESS CrossNetPayState = 3
	CrossNetPayState_XNET_EGRESS  CrossNetPayState = 4
)

// Enum value maps for CrossNetPayState.
var (
	CrossNetPayState_name = map[int32]string{
		0: "XNET_NULL",
		1: "XNET_SRC",
		2: "XNET_DST",
		3: "XNET_INGRESS",
		4: "XNET_EGRESS",
	}
	CrossNetPayState_value = map[string]int32{
		"XNET_NULL":    0,
		"XNET_SRC":     1,
		"XNET_DST":     2,
		"XNET_INGRESS": 3,
		"XNET_EGRESS":  4,
	}
)

func (x CrossNetPayState) Enum() *CrossNetPayState {
	p := new(CrossNetPayState)
	*p = x
	return p
}

func (x CrossNetPayState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrossNetPayState) Descriptor() protoreflect.EnumDescriptor {
	return file_pem_proto_enumTypes[1].Descriptor()
}

func (CrossNetPayState) Type() protoreflect.EnumType {
	return &file_pem_proto_enumTypes[1]
}

func (x CrossNetPayState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrossNetPayState.Descriptor instead.
func (CrossNetPayState) EnumDescriptor() ([]byte, []int) {
	return file_pem_proto_rawDescGZIP(), []int{1}
}

// Next tag: 30
type PayEventMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  PayMessageType         `protobuf:"varint,1,opt,name=type,proto3,enum=pem.PayMessageType" json:"type,omitempty"` // all
	// pay_id this message is about.
	PayId string `protobuf:"bytes,2,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"` // pay req in, out local/remote, pay resp, settle resp
	// token used by the pay.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // pay req in
	// message src
	Src string `protobuf:"bytes,5,opt,name=src,proto3" json:"src,omitempty"` // pay req in
	// message dst
	Dst string `protobuf:"bytes,6,opt,name=dst,proto3" json:"dst,omitempty"` // pay req out local/remote
	// direct peer the message comes from.
	MsgFrom string `protobuf:"bytes,7,opt,name=msg_from,json=msgFrom,proto3" json:"msg_from,omitempty"` // all
	// secret of the pay hash lock.
	Secret string `protobuf:"bytes,8,opt,name=secret,proto3" json:"secret,omitempty"`
	// reason of pay settlement
	SettleReason rpc.PaymentSettleReason `protobuf:"varint,9,opt,name=settle_reason,json=settleReason,proto3,enum=rpc.PaymentSettleReason" json:"settle_reason,omitempty"`
	// direct peer the message goes to.
	MsgTo string `protobuf:"bytes,10,opt,name=msg_to,json=msgTo,proto3" json:"msg_to,omitempty"` // pay req in, pay resp, settle resp
	// which machine processed the message
	Machine string `protobuf:"bytes,11,opt,name=machine,proto3" json:"machine,omitempty"` // all
	// cid this message comes from
	FromCid string `protobuf:"bytes,12,opt,name=from_cid,json=fromCid,proto3" json:"from_cid,omitempty"` // pay req in
	// cid this message goes to
	ToCid string `protobuf:"bytes,13,opt,name=to_cid,json=toCid,proto3" json:"to_cid,omitempty"` // pay req out local/remote, pay resp, settle resp
	// error occured during message processing
	Error []string `protobuf:"bytes,14,rep,name=error,proto3" json:"error,omitempty"`
	// start timestamp of message processing
	StartTimeStamp int64 `protobuf:"varint,15,opt,name=start_time_stamp,json=startTimeStamp,proto3" json:"start_time_stamp,omitempty"`
	// end timestamp of message processing
	EndTimeStamp int64 `protobuf:"varint,16,opt,name=end_time_stamp,json=endTimeStamp,proto3" json:"end_time_stamp,omitempty"`
	// execution time in milliseconds
	ExecutionTimeMs float32 `protobuf:"fixed32,17,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	// if exists in ack msg, the message may contains several pays and this field is complete pay id set.
	PayIds []string `protobuf:"bytes,20,rep,name=pay_ids,json=payIds,proto3" json:"pay_ids,omitempty"` // cond pay resp, settle pay resp
	// if exists in nack msg, the message may contains several pays and this field is complete pay id set.
	NackPayIds []string `protobuf:"bytes,21,rep,name=nack_pay_ids,json=nackPayIds,proto3" json:"nack_pay_ids,omitempty"` // cond pay resp, settle pay resp
	// indicating if this machine that processes the message is forwarding out message outside the OSP.
	ForwardingExternal bool `protobuf:"varint,22,opt,name=forwarding_external,json=forwardingExternal,proto3" json:"forwarding_external,omitempty"`
	// simplex sequence numbers
	SeqNums *SimplexSeqNums `protobuf:"bytes,23,opt,name=seq_nums,json=seqNums,proto3" json:"seq_nums,omitempty"`
	// error returned in the nack message
	Nack *rpc.Error `protobuf:"bytes,24,opt,name=nack,proto3" json:"nack,omitempty"`
	// resend messages due to nack
	Resend []*PayEventMessage `protobuf:"bytes,25,rep,name=resend,proto3" json:"resend,omitempty"`
	// event is part of a direct-payment
	DirectPay bool `protobuf:"varint,26,opt,name=direct_pay,json=directPay,proto3" json:"direct_pay,omitempty"`
	// When filled, it means the node tries to delegate receiving the pay. This field logs delegation description
	DelegationDescription *rpc.DelegationDescription `protobuf:"bytes,27,opt,name=delegation_description,json=delegationDescription,proto3" json:"delegation_description,omitempty"`
	// pay routing path
	PayPath string `protobuf:"bytes,28,opt,name=pay_path,json=payPath,proto3" json:"pay_path,omitempty"`
	// cross net payment info
	Xnet          *CrossNetInfo `protobuf:"bytes,29,opt,name=xnet,proto3" json:"xnet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayEventMessage) Reset() {
	*x = PayEventMessage{}
	mi := &file_pem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayEventMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayEventMessage) ProtoMessage() {}

func (x *PayEventMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayEventMessage.ProtoReflect.Descriptor instead.
func (*PayEventMessage) Descriptor() ([]byte, []int) {
	return file_pem_proto_rawDescGZIP(), []int{0}
}

func (x *PayEventMessage) GetType() PayMessageType {
	if x != nil {
		return x.Type
	}
	return PayMessageType_UNDEFINED_TYPE
}

func (x *PayEventMessage) GetPayId() string {
	if x != nil {
		return x.PayId
	}
	return ""
}

func (x *PayEventMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PayEventMessage) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *PayEventMessage) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *PayEventMessage) GetMsgFrom() string {
	if x != nil {
		return x.MsgFrom
	}
	return ""
}

func (x *PayEventMessage) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *PayEventMessage) GetSettleReason() rpc.PaymentSettleReason {
	if x != nil {
		return x.SettleReason
	}
	return rpc.PaymentSettleReason(0)
}

func (x *PayEventMessage) GetMsgTo() string {
	if x != nil {
		return x.MsgTo
	}
	return ""
}

func (x *PayEventMessage) GetMachine() string {
	if x != nil {
		return x.Machine
	}
	return ""
}

func (x *PayEventMessage) GetFromCid() string {
	if x != nil {
		return x.FromCid
	}
	return ""
}

func (x *PayEventMessage) GetToCid() string {
	if x != nil {
		return x.ToCid
	}
	return ""
}

func (x *PayEventMessage) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *PayEventMessage) GetStartTimeStamp() int64 {
	if x != nil {
		return x.StartTimeStamp
	}
	return 0
}

func (x *PayEventMessage) GetEndTimeStamp() int64 {
	if x != nil {
		return x.EndTimeStamp
	}
	return 0
}

func (x *PayEventMessage) GetExecutionTimeMs() float32 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *PayEventMessage) GetPayIds() []string {
	if x != nil {
		return x.PayIds
	}
	return nil
}

func (x *PayEventMessage) GetNackPayIds() []string {
	if x != nil {
		return x.NackPayIds
	}
	return nil
}

func (x *PayEventMessage) GetForwardingExternal() bool {
	if x != nil {
		return x.ForwardingExternal
	}
	return false
}

func (x *PayEventMessage) GetSeqNums() *SimplexSeqNums {
	if x != nil {
		return x.SeqNums
	}
	return nil
}

func (x *PayEventMessage) GetNack() *rpc.Error {
	if x != nil {
		return x.Nack
	}
	return nil
}

func (x *PayEventMessage) GetResend() []*PayEventMessage {
	if x != nil {
		return x.Resend
	}
	return nil
}

func (x *PayEventMessage) GetDirectPay() bool {
	if x != nil {
		return x.DirectPay
	}
	return false
}

func (x *PayEventMessage) GetDelegationDescription() *rpc.DelegationDescription {
	if x != nil {
		return x.DelegationDescription
	}
	return nil
}

func (x *PayEventMessage) GetPayPath() string {
	if x != nil {
		return x.PayPath
	}
	return ""
}

func (x *PayEventMessage) GetXnet() *CrossNetInfo {
	if x != nil {
		return x.Xnet
	}
	return nil
}

type SimplexSeqNums struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sequence number sent in outgoing message.
	Out uint64 `protobuf:"varint,1,opt,name=out,proto3" json:"out,omitempty"`
	// base of sequence number sent in outgoing message.
	OutBase uint64 `protobuf:"varint,2,opt,name=out_base,json=outBase,proto3" json:"out_base,omitempty"`
	// sequence number of received message
	In uint64 `protobuf:"varint,3,opt,name=in,proto3" json:"in,omitempty"`
	// base sequence number of received message
	InBase uint64 `protobuf:"varint,4,opt,name=in_base,json=inBase,proto3" json:"in_base,omitempty"`
	// stored co-signed simplex sequence number
	Stored uint64 `protobuf:"varint,5,opt,name=stored,proto3" json:"stored,omitempty"`
	// sequence number acked by the message
	Ack uint64 `protobuf:"varint,6,opt,name=ack,proto3" json:"ack,omitempty"`
	// highest inflight sequence number, usually needed only when there is a nack to trigger resend
	LastInflight  uint64 `protobuf:"varint,7,opt,name=last_inflight,json=lastInflight,proto3" json:"last_inflight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimplexSeqNums) Reset() {
	*x = SimplexSeqNums{}
	mi := &file_pem_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimplexSeqNums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimplexSeqNums) ProtoMessage() {}

func (x *SimplexSeqNums) ProtoReflect() protoreflect.Message {
	mi := &file_pem_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimplexSeqNums.ProtoReflect.Descriptor instead.
func (*SimplexSeqNums) Descriptor() ([]byte, []int) {
	return file_pem_proto_rawDescGZIP(), []int{1}
}

func (x *SimplexSeqNums) GetOut() uint64 {
	if x != nil {
		return x.Out
	}
	return 0
}

func (x *SimplexSeqNums) GetOutBase() uint64 {
	if x != nil {
		return x.OutBase
	}
	return 0
}

func (x *SimplexSeqNums) GetIn() uint64 {
	if x != nil {
		return x.In
	}
	return 0
}

func (x *SimplexSeqNums) GetInBase() uint64 {
	if x != nil {
		return x.InBase
	}
	return 0
}

func (x *SimplexSeqNums) GetStored() uint64 {
	if x != nil {
		return x.Stored
	}
	return 0
}

func (x *SimplexSeqNums) GetAck() uint64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *SimplexSeqNums) GetLastInflight() uint64 {
	if x != nil {
		return x.LastInflight
	}
	return 0
}

type CrossNetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcNetId      uint64                 `protobuf:"varint,1,opt,name=src_net_id,json=srcNetId,proto3" json:"src_net_id,omitempty"`
	DstNetId      uint64                 `protobuf:"varint,2,opt,name=dst_net_id,json=dstNetId,proto3" json:"dst_net_id,omitempty"`
	OriginalPayId string                 `protobuf:"bytes,3,opt,name=original_pay_id,json=originalPayId,proto3" json:"original_pay_id,omitempty"`
	FromPayId     string                 `protobuf:"bytes,4,opt,name=from_pay_id,json=fromPayId,proto3" json:"from_pay_id,omitempty"`
	ToBridgeAddr  string                 `protobuf:"bytes,5,opt,name=to_bridge_addr,json=toBridgeAddr,proto3" json:"to_bridge_addr,omitempty"`
	ToBridgeNetId uint64                 `protobuf:"varint,6,opt,name=to_bridge_net_id,json=toBridgeNetId,proto3" json:"to_bridge_net_id,omitempty"`
	FromBridgeId  uint64                 `protobuf:"varint,7,opt,name=from_bridge_id,json=fromBridgeId,proto3" json:"from_bridge_id,omitempty"`
	State         CrossNetPayState       `protobuf:"varint,8,opt,name=state,proto3,enum=pem.CrossNetPayState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossNetInfo) Reset() {
	*x = CrossNetInfo{}
	mi := &file_pem_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossNetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossNetInfo) ProtoMessage() {}

func (x *CrossNetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pem_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossNetInfo.ProtoReflect.Descriptor instead.
func (*CrossNetInfo) Descriptor() ([]byte, []int) {
	return file_pem_proto_rawDescGZIP(), []int{2}
}

func (x *CrossNetInfo) GetSrcNetId() uint64 {
	if x != nil {
		return x.SrcNetId
	}
	return 0
}

func (x *CrossNetInfo) GetDstNetId() uint64 {
	if x != nil {
		return x.DstNetId
	}
	return 0
}

func (x *CrossNetInfo) GetOriginalPayId() string {
	if x != nil {
		return x.OriginalPayId
	}
	return ""
}

func (x *CrossNetInfo) GetFromPayId() string {
	if x != nil {
		return x.FromPayId
	}
	return ""
}

func (x *CrossNetInfo) GetToBridgeAddr() string {
	if x != nil {
		return x.ToBridgeAddr
	}
	return ""
}

func (x *CrossNetInfo) GetToBridgeNetId() uint64 {
	if x != nil {
		return x.ToBridgeNetId
	}
	return 0
}

func (x *CrossNetInfo) GetFromBridgeId() uint64 {
	if x != nil {
		return x.FromBridgeId
	}
	return 0
}

func (x *CrossNetInfo) GetState() CrossNetPayState {
	if x != nil {
		return x.State
	}
	return CrossNetPayState_XNET_NULL
}

var File_pem_proto protoreflect.FileDescriptor

const file_pem_proto_rawDesc = "" +
	"\n" +
	"\tpem.proto\x12\x03pem\x1a\rmessage.proto\"\x90\a\n" +
	"\x0fPayEventMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.pem.PayMessageTypeR\x04type\x12\x15\n" +
	"\x06pay_id\x18\x02 \x01(\tR\x05payId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x10\n" +
	"\x03src\x18\x05 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x06 \x01(\tR\x03dst\x12\x19\n" +
	"\bmsg_from\x18\a \x01(\tR\amsgFrom\x12\x16\n" +
	"\x06secret\x18\b \x01(\tR\x06secret\x12=\n" +
	"\rsettle_reason\x18\t \x01(\x0e2\x18.rpc.PaymentSettleReasonR\fsettleReason\x12\x15\n" +
	"\x06msg_to\x18\n" +
	" \x01(\tR\x05msgTo\x12\x18\n" +
	"\amachine\x18\v \x01(\tR\amachine\x12\x19\n" +
	"\bfrom_cid\x18\f \x01(\tR\afromCid\x12\x15\n" +
	"\x06to_cid\x18\r \x01(\tR\x05toCid\x12\x14\n" +
	"\x05error\x18\x0e \x03(\tR\x05error\x12(\n" +
	"\x10start_time_stamp\x18\x0f \x01(\x03R\x0estartTimeStamp\x12$\n" +
	"\x0eend_time_stamp\x18\x10 \x01(\x03R\fendTimeStamp\x12*\n" +
	"\x11execution_time_ms\x18\x11 \x01(\x02R\x0fexecutionTimeMs\x12\x17\n" +
	"\apay_ids\x18\x14 \x03(\tR\x06payIds\x12 \n" +
	"\fnack_pay_ids\x18\x15 \x03(\tR\n" +
	"nackPayIds\x12/\n" +
	"\x13forwarding_external\x18\x16 \x01(\bR\x12forwardingExternal\x12.\n" +
	"\bseq_nums\x18\x17 \x01(\v2\x13.pem.SimplexSeqNumsR\aseqNums\x12\x1e\n" +
	"\x04nack\x18\x18 \x01(\v2\n" +
	".rpc.ErrorR\x04nack\x12,\n" +
	"\x06resend\x18\x19 \x03(\v2\x14.pem.PayEventMessageR\x06resend\x12\x1d\n" +
	"\n" +
	"direct_pay\x18\x1a \x01(\bR\tdirectPay\x12Q\n" +
	"\x16delegation_description\x18\x1b \x01(\v2\x1a.rpc.DelegationDescriptionR\x15delegationDescription\x12\x19\n" +
	"\bpay_path\x18\x1c \x01(\tR\apayPath\x12%\n" +
	"\x04xnet\x18\x1d \x01(\v2\x11.pem.CrossNetInfoR\x04xnet\"\xb5\x01\n" +
	"\x0eSimplexSeqNums\x12\x10\n" +
	"\x03out\x18\x01 \x01(\x04R\x03out\x12\x19\n" +
	"\bout_base\x18\x02 \x01(\x04R\aoutBase\x12\x0e\n" +
	"\x02in\x18\x03 \x01(\x04R\x02in\x12\x17\n" +
	"\ain_base\x18\x04 \x01(\x04R\x06inBase\x12\x16\n" +
	"\x06stored\x18\x05 \x01(\x04R\x06stored\x12\x10\n" +
	"\x03ack\x18\x06 \x01(\x04R\x03ack\x12#\n" +
	"\rlast_inflight\x18\a \x01(\x04R\flastInflight\"\xb4\x02\n" +
	"\fCrossNetInfo\x12\x1c\n" +
	"\n" +
	"src_net_id\x18\x01 \x01(\x04R\bsrcNetId\x12\x1c\n" +
	"\n" +
	"dst_net_id\x18\x02 \x01(\x04R\bdstNetId\x12&\n" +
	"\x0foriginal_pay_id\x18\x03 \x01(\tR\roriginalPayId\x12\x1e\n" +
	"\vfrom_pay_id\x18\x04 \x01(\tR\tfromPayId\x12$\n" +
	"\x0eto_bridge_addr\x18\x05 \x01(\tR\ftoBridgeAddr\x12'\n" +
	"\x10to_bridge_net_id\x18\x06 \x01(\x04R\rtoBridgeNetId\x12$\n" +
	"\x0efrom_bridge_id\x18\a \x01(\x04R\ffromBridgeId\x12+\n" +
	"\x05state\x18\b \x01(\x0e2\x15.pem.CrossNetPayStateR\x05state*\xeb\x03\n" +
	"\x0ePayMessageType\x12\x12\n" +
	"\x0eUNDEFINED_TYPE\x10\x00\x12\x14\n" +
	"\x10COND_PAY_REQUEST\x10\x01\x12\x15\n" +
	"\x11COND_PAY_RESPONSE\x10\x02\x12\x14\n" +
	"\x10COND_PAY_RECEIPT\x10\x03\x12\x11\n" +
	"\rREVEAL_SECRET\x10\x04\x12\x15\n" +
	"\x11REVEAL_SECRET_ACK\x10\x05\x12\x14\n" +
	"\x10PAY_SETTLE_PROOF\x10\x06\x12\x16\n" +
	"\x12PAY_SETTLE_REQUEST\x10\a\x12\x17\n" +
	"\x13PAY_SETTLE_RESPONSE\x10\b\x12\x12\n" +
	"\x0eSEND_TOKEN_API\x10\t\x12\x1e\n" +
	"\x1aSRC_SETTLE_EXPIRED_PAY_API\x10\n" +
	"\x12\x1e\n" +
	"\x1aDST_SETTLE_EXPIRED_PAY_API\x10\v\x12\x1c\n" +
	"\x18CONFIRM_ON_CHAIN_PAY_API\x10\f\x12\x1a\n" +
	"\x16REJECT_BOOLEAN_PAY_API\x10\r\x12$\n" +
	" SETTLE_ON_CHAIN_RESOLVED_PAY_API\x10\x0e\x12\x14\n" +
	"\x10WITHDRAW_REQUEST\x10\x0f\x12\x15\n" +
	"\x11WITHDRAW_RESPONSE\x10\x10\x12\x1b\n" +
	"\x17CONFIRM_BOOLEAN_PAY_API\x10\x11\x12\x13\n" +
	"\x0fROUTING_REQUEST\x10\x12*`\n" +
	"\x10CrossNetPayState\x12\r\n" +
	"\tXNET_NULL\x10\x00\x12\f\n" +
	"\bXNET_SRC\x10\x01\x12\f\n" +
	"\bXNET_DST\x10\x02\x12\x10\n" +
	"\fXNET_INGRESS\x10\x03\x12\x0f\n" +
	"\vXNET_EGRESS\x10\x04B(Z&github.com/celer-network/agent-pay/pemb\x06proto3"

var (
	file_pem_proto_rawDescOnce sync.Once
	file_pem_proto_rawDescData []byte
)

func file_pem_proto_rawDescGZIP() []byte {
	file_pem_proto_rawDescOnce.Do(func() {
		file_pem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pem_proto_rawDesc), len(file_pem_proto_rawDesc)))
	})
	return file_pem_proto_rawDescData
}

var file_pem_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pem_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pem_proto_goTypes = []any{
	(PayMessageType)(0),               // 0: pem.PayMessageType
	(CrossNetPayState)(0),             // 1: pem.CrossNetPayState
	(*PayEventMessage)(nil),           // 2: pem.PayEventMessage
	(*SimplexSeqNums)(nil),            // 3: pem.SimplexSeqNums
	(*CrossNetInfo)(nil),              // 4: pem.CrossNetInfo
	(rpc.PaymentSettleReason)(0),      // 5: rpc.PaymentSettleReason
	(*rpc.Error)(nil),                 // 6: rpc.Error
	(*rpc.DelegationDescription)(nil), // 7: rpc.DelegationDescription
}
var file_pem_proto_depIdxs = []int32{
	0, // 0: pem.PayEventMessage.type:type_name -> pem.PayMessageType
	5, // 1: pem.PayEventMessage.settle_reason:type_name -> rpc.PaymentSettleReason
	3, // 2: pem.PayEventMessage.seq_nums:type_name -> pem.SimplexSeqNums
	6, // 3: pem.PayEventMessage.nack:type_name -> rpc.Error
	2, // 4: pem.PayEventMessage.resend:type_name -> pem.PayEventMessage
	7, // 5: pem.PayEventMessage.delegation_description:type_name -> rpc.DelegationDescription
	4, // 6: pem.PayEventMessage.xnet:type_name -> pem.CrossNetInfo
	1, // 7: pem.CrossNetInfo.state:type_name -> pem.CrossNetPayState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pem_proto_init() }
func file_pem_proto_init() {
	if File_pem_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pem_proto_rawDesc), len(file_pem_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pem_proto_goTypes,
		DependencyIndexes: file_pem_proto_depIdxs,
		EnumInfos:         file_pem_proto_enumTypes,
		MessageInfos:      file_pem_proto_msgTypes,
	}.Build()
	File_pem_proto = out.File
	file_pem_proto_goTypes = nil
	file_pem_proto_depIdxs = nil
}
