// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// InternalWebApiClient is the client API for InternalWebApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalWebApiClient interface {
	OpenTrustedPaymentChannel(ctx context.Context, in *OpenPaymentChannelRequest, opts ...grpc.CallOption) (*ChannelID, error)
	InstantiateTrustedPaymentChannel(ctx context.Context, in *TokenInfo, opts ...grpc.CallOption) (*ChannelID, error)
	DepositNonBlocking(ctx context.Context, in *DepositOrWithdrawRequest, opts ...grpc.CallOption) (*DepositOrWithdrawJob, error)
	CooperativeWithdrawNonBlocking(ctx context.Context, in *DepositOrWithdrawRequest, opts ...grpc.CallOption) (*DepositOrWithdrawJob, error)
}

type internalWebApiClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalWebApiClient(cc grpc.ClientConnInterface) InternalWebApiClient {
	return &internalWebApiClient{cc}
}

func (c *internalWebApiClient) OpenTrustedPaymentChannel(ctx context.Context, in *OpenPaymentChannelRequest, opts ...grpc.CallOption) (*ChannelID, error) {
	out := new(ChannelID)
	err := c.cc.Invoke(ctx, "/webrpc.InternalWebApi/OpenTrustedPaymentChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalWebApiClient) InstantiateTrustedPaymentChannel(ctx context.Context, in *TokenInfo, opts ...grpc.CallOption) (*ChannelID, error) {
	out := new(ChannelID)
	err := c.cc.Invoke(ctx, "/webrpc.InternalWebApi/InstantiateTrustedPaymentChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalWebApiClient) DepositNonBlocking(ctx context.Context, in *DepositOrWithdrawRequest, opts ...grpc.CallOption) (*DepositOrWithdrawJob, error) {
	out := new(DepositOrWithdrawJob)
	err := c.cc.Invoke(ctx, "/webrpc.InternalWebApi/DepositNonBlocking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalWebApiClient) CooperativeWithdrawNonBlocking(ctx context.Context, in *DepositOrWithdrawRequest, opts ...grpc.CallOption) (*DepositOrWithdrawJob, error) {
	out := new(DepositOrWithdrawJob)
	err := c.cc.Invoke(ctx, "/webrpc.InternalWebApi/CooperativeWithdrawNonBlocking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalWebApiServer is the server API for InternalWebApi service.
// All implementations should embed UnimplementedInternalWebApiServer
// for forward compatibility
type InternalWebApiServer interface {
	OpenTrustedPaymentChannel(context.Context, *OpenPaymentChannelRequest) (*ChannelID, error)
	InstantiateTrustedPaymentChannel(context.Context, *TokenInfo) (*ChannelID, error)
	DepositNonBlocking(context.Context, *DepositOrWithdrawRequest) (*DepositOrWithdrawJob, error)
	CooperativeWithdrawNonBlocking(context.Context, *DepositOrWithdrawRequest) (*DepositOrWithdrawJob, error)
}

// UnimplementedInternalWebApiServer should be embedded to have forward compatible implementations.
type UnimplementedInternalWebApiServer struct {
}

func (UnimplementedInternalWebApiServer) OpenTrustedPaymentChannel(context.Context, *OpenPaymentChannelRequest) (*ChannelID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTrustedPaymentChannel not implemented")
}
func (UnimplementedInternalWebApiServer) InstantiateTrustedPaymentChannel(context.Context, *TokenInfo) (*ChannelID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstantiateTrustedPaymentChannel not implemented")
}
func (UnimplementedInternalWebApiServer) DepositNonBlocking(context.Context, *DepositOrWithdrawRequest) (*DepositOrWithdrawJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositNonBlocking not implemented")
}
func (UnimplementedInternalWebApiServer) CooperativeWithdrawNonBlocking(context.Context, *DepositOrWithdrawRequest) (*DepositOrWithdrawJob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CooperativeWithdrawNonBlocking not implemented")
}

// UnsafeInternalWebApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalWebApiServer will
// result in compilation errors.
type UnsafeInternalWebApiServer interface {
	mustEmbedUnimplementedInternalWebApiServer()
}

func RegisterInternalWebApiServer(s *grpc.Server, srv InternalWebApiServer) {
	s.RegisterService(&_InternalWebApi_serviceDesc, srv)
}

func _InternalWebApi_OpenTrustedPaymentChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenPaymentChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalWebApiServer).OpenTrustedPaymentChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrpc.InternalWebApi/OpenTrustedPaymentChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalWebApiServer).OpenTrustedPaymentChannel(ctx, req.(*OpenPaymentChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalWebApi_InstantiateTrustedPaymentChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalWebApiServer).InstantiateTrustedPaymentChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrpc.InternalWebApi/InstantiateTrustedPaymentChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalWebApiServer).InstantiateTrustedPaymentChannel(ctx, req.(*TokenInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalWebApi_DepositNonBlocking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositOrWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalWebApiServer).DepositNonBlocking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrpc.InternalWebApi/DepositNonBlocking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalWebApiServer).DepositNonBlocking(ctx, req.(*DepositOrWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InternalWebApi_CooperativeWithdrawNonBlocking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositOrWithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalWebApiServer).CooperativeWithdrawNonBlocking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webrpc.InternalWebApi/CooperativeWithdrawNonBlocking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalWebApiServer).CooperativeWithdrawNonBlocking(ctx, req.(*DepositOrWithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InternalWebApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webrpc.InternalWebApi",
	HandlerType: (*InternalWebApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTrustedPaymentChannel",
			Handler:    _InternalWebApi_OpenTrustedPaymentChannel_Handler,
		},
		{
			MethodName: "InstantiateTrustedPaymentChannel",
			Handler:    _InternalWebApi_InstantiateTrustedPaymentChannel_Handler,
		},
		{
			MethodName: "DepositNonBlocking",
			Handler:    _InternalWebApi_DepositNonBlocking_Handler,
		},
		{
			MethodName: "CooperativeWithdrawNonBlocking",
			Handler:    _InternalWebApi_CooperativeWithdrawNonBlocking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal_web_api.proto",
}
