// Copyright 2018-2025 Celer Network

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: internal_web_api.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_internal_web_api_proto protoreflect.FileDescriptor

const file_internal_web_api_proto_rawDesc = "" +
	"\n" +
	"\x16internal_web_api.proto\x12\x06webrpc\x1a\rweb_api.proto2\xed\x02\n" +
	"\x0eInternalWebApi\x12S\n" +
	"\x19OpenTrustedPaymentChannel\x12!.webrpc.OpenPaymentChannelRequest\x1a\x11.webrpc.ChannelID\"\x00\x12J\n" +
	" InstantiateTrustedPaymentChannel\x12\x11.webrpc.TokenInfo\x1a\x11.webrpc.ChannelID\"\x00\x12V\n" +
	"\x12DepositNonBlocking\x12 .webrpc.DepositOrWithdrawRequest\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12b\n" +
	"\x1eCooperativeWithdrawNonBlocking\x12 .webrpc.DepositOrWithdrawRequest\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00B/Z-github.com/celer-network/agent-pay/webapi/rpcb\x06proto3"

var file_internal_web_api_proto_goTypes = []any{
	(*OpenPaymentChannelRequest)(nil), // 0: webrpc.OpenPaymentChannelRequest
	(*TokenInfo)(nil),                 // 1: webrpc.TokenInfo
	(*DepositOrWithdrawRequest)(nil),  // 2: webrpc.DepositOrWithdrawRequest
	(*ChannelID)(nil),                 // 3: webrpc.ChannelID
	(*DepositOrWithdrawJob)(nil),      // 4: webrpc.DepositOrWithdrawJob
}
var file_internal_web_api_proto_depIdxs = []int32{
	0, // 0: webrpc.InternalWebApi.OpenTrustedPaymentChannel:input_type -> webrpc.OpenPaymentChannelRequest
	1, // 1: webrpc.InternalWebApi.InstantiateTrustedPaymentChannel:input_type -> webrpc.TokenInfo
	2, // 2: webrpc.InternalWebApi.DepositNonBlocking:input_type -> webrpc.DepositOrWithdrawRequest
	2, // 3: webrpc.InternalWebApi.CooperativeWithdrawNonBlocking:input_type -> webrpc.DepositOrWithdrawRequest
	3, // 4: webrpc.InternalWebApi.OpenTrustedPaymentChannel:output_type -> webrpc.ChannelID
	3, // 5: webrpc.InternalWebApi.InstantiateTrustedPaymentChannel:output_type -> webrpc.ChannelID
	4, // 6: webrpc.InternalWebApi.DepositNonBlocking:output_type -> webrpc.DepositOrWithdrawJob
	4, // 7: webrpc.InternalWebApi.CooperativeWithdrawNonBlocking:output_type -> webrpc.DepositOrWithdrawJob
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_web_api_proto_init() }
func file_internal_web_api_proto_init() {
	if File_internal_web_api_proto != nil {
		return
	}
	file_web_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_web_api_proto_rawDesc), len(file_internal_web_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_web_api_proto_goTypes,
		DependencyIndexes: file_internal_web_api_proto_depIdxs,
	}.Build()
	File_internal_web_api_proto = out.File
	file_internal_web_api_proto_goTypes = nil
	file_internal_web_api_proto_depIdxs = nil
}
