// Copyright 2018-2025 Celer Network

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: web_api.proto

package rpc

import (
	entity "github.com/celer-network/agent-pay/entity"
	rpc "github.com/celer-network/agent-pay/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next tag: 3
type GetPayHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromStart     bool                   `protobuf:"varint,1,opt,name=from_start,json=fromStart,proto3" json:"from_start,omitempty"`
	ItemsPerPage  int32                  `protobuf:"varint,2,opt,name=itemsPerPage,proto3" json:"itemsPerPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayHistoryRequest) Reset() {
	*x = GetPayHistoryRequest{}
	mi := &file_web_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayHistoryRequest) ProtoMessage() {}

func (x *GetPayHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPayHistoryRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetPayHistoryRequest) GetFromStart() bool {
	if x != nil {
		return x.FromStart
	}
	return false
}

func (x *GetPayHistoryRequest) GetItemsPerPage() int32 {
	if x != nil {
		return x.ItemsPerPage
	}
	return 0
}

// Next tag: 3
type GetPayHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pays          []*rpc.OneHistoricalPay `protobuf:"bytes,1,rep,name=pays,proto3" json:"pays,omitempty"`
	HasMoreResult bool                    `protobuf:"varint,2,opt,name=has_more_result,json=hasMoreResult,proto3" json:"has_more_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayHistoryResponse) Reset() {
	*x = GetPayHistoryResponse{}
	mi := &file_web_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayHistoryResponse) ProtoMessage() {}

func (x *GetPayHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPayHistoryResponse) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPayHistoryResponse) GetPays() []*rpc.OneHistoricalPay {
	if x != nil {
		return x.Pays
	}
	return nil
}

func (x *GetPayHistoryResponse) GetHasMoreResult() bool {
	if x != nil {
		return x.HasMoreResult
	}
	return false
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     entity.TokenType       `protobuf:"varint,1,opt,name=token_type,json=tokenType,proto3,enum=entity.TokenType" json:"token_type,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=token_address,json=tokenAddress,proto3" json:"token_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_web_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{2}
}

func (x *TokenInfo) GetTokenType() entity.TokenType {
	if x != nil {
		return x.TokenType
	}
	return entity.TokenType(0)
}

func (x *TokenInfo) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

type SetDelegationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenInfos    []*TokenInfo           `protobuf:"bytes,1,rep,name=token_infos,json=tokenInfos,proto3" json:"token_infos,omitempty"`
	BlockDuration int64                  `protobuf:"varint,2,opt,name=block_duration,json=blockDuration,proto3" json:"block_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDelegationRequest) Reset() {
	*x = SetDelegationRequest{}
	mi := &file_web_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDelegationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDelegationRequest) ProtoMessage() {}

func (x *SetDelegationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDelegationRequest.ProtoReflect.Descriptor instead.
func (*SetDelegationRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{3}
}

func (x *SetDelegationRequest) GetTokenInfos() []*TokenInfo {
	if x != nil {
		return x.TokenInfos
	}
	return nil
}

func (x *SetDelegationRequest) GetBlockDuration() int64 {
	if x != nil {
		return x.BlockDuration
	}
	return 0
}

type OpenPaymentChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenInfo     *TokenInfo             `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PeerAmount    string                 `protobuf:"bytes,3,opt,name=peer_amount,json=peerAmount,proto3" json:"peer_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenPaymentChannelRequest) Reset() {
	*x = OpenPaymentChannelRequest{}
	mi := &file_web_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenPaymentChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenPaymentChannelRequest) ProtoMessage() {}

func (x *OpenPaymentChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenPaymentChannelRequest.ProtoReflect.Descriptor instead.
func (*OpenPaymentChannelRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{4}
}

func (x *OpenPaymentChannelRequest) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *OpenPaymentChannelRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OpenPaymentChannelRequest) GetPeerAmount() string {
	if x != nil {
		return x.PeerAmount
	}
	return ""
}

type ChannelID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelID) Reset() {
	*x = ChannelID{}
	mi := &file_web_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelID) ProtoMessage() {}

func (x *ChannelID) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelID.ProtoReflect.Descriptor instead.
func (*ChannelID) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{5}
}

func (x *ChannelID) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type DepositOrWithdrawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenInfo     *TokenInfo             `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositOrWithdrawRequest) Reset() {
	*x = DepositOrWithdrawRequest{}
	mi := &file_web_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositOrWithdrawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOrWithdrawRequest) ProtoMessage() {}

func (x *DepositOrWithdrawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOrWithdrawRequest.ProtoReflect.Descriptor instead.
func (*DepositOrWithdrawRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{6}
}

func (x *DepositOrWithdrawRequest) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *DepositOrWithdrawRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type DepositOrWithdrawJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TxHash        string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositOrWithdrawJob) Reset() {
	*x = DepositOrWithdrawJob{}
	mi := &file_web_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositOrWithdrawJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositOrWithdrawJob) ProtoMessage() {}

func (x *DepositOrWithdrawJob) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositOrWithdrawJob.ProtoReflect.Descriptor instead.
func (*DepositOrWithdrawJob) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{7}
}

func (x *DepositOrWithdrawJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *DepositOrWithdrawJob) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type GetBalanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FreeBalance       string                 `protobuf:"bytes,1,opt,name=free_balance,json=freeBalance,proto3" json:"free_balance,omitempty"`
	LockedBalance     string                 `protobuf:"bytes,2,opt,name=locked_balance,json=lockedBalance,proto3" json:"locked_balance,omitempty"`
	ReceivingCapacity string                 `protobuf:"bytes,3,opt,name=receiving_capacity,json=receivingCapacity,proto3" json:"receiving_capacity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_web_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetBalanceResponse) GetFreeBalance() string {
	if x != nil {
		return x.FreeBalance
	}
	return ""
}

func (x *GetBalanceResponse) GetLockedBalance() string {
	if x != nil {
		return x.LockedBalance
	}
	return ""
}

func (x *GetBalanceResponse) GetReceivingCapacity() string {
	if x != nil {
		return x.ReceivingCapacity
	}
	return ""
}

type GetPeerFreeBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenInfo     *TokenInfo             `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	PeerAddress   string                 `protobuf:"bytes,2,opt,name=peer_address,json=peerAddress,proto3" json:"peer_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerFreeBalanceRequest) Reset() {
	*x = GetPeerFreeBalanceRequest{}
	mi := &file_web_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerFreeBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerFreeBalanceRequest) ProtoMessage() {}

func (x *GetPeerFreeBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerFreeBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetPeerFreeBalanceRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetPeerFreeBalanceRequest) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *GetPeerFreeBalanceRequest) GetPeerAddress() string {
	if x != nil {
		return x.PeerAddress
	}
	return ""
}

type FreeBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreeBalance   string                 `protobuf:"bytes,1,opt,name=free_balance,json=freeBalance,proto3" json:"free_balance,omitempty"`
	JoinStatus    int32                  `protobuf:"varint,2,opt,name=join_status,json=joinStatus,proto3" json:"join_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeBalance) Reset() {
	*x = FreeBalance{}
	mi := &file_web_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeBalance) ProtoMessage() {}

func (x *FreeBalance) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeBalance.ProtoReflect.Descriptor instead.
func (*FreeBalance) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{10}
}

func (x *FreeBalance) GetFreeBalance() string {
	if x != nil {
		return x.FreeBalance
	}
	return ""
}

func (x *FreeBalance) GetJoinStatus() int32 {
	if x != nil {
		return x.JoinStatus
	}
	return 0
}

type Condition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OnChainDeployed bool                   `protobuf:"varint,1,opt,name=on_chain_deployed,json=onChainDeployed,proto3" json:"on_chain_deployed,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	IsFinalizedArgs []byte                 `protobuf:"bytes,3,opt,name=is_finalized_args,json=isFinalizedArgs,proto3" json:"is_finalized_args,omitempty"`
	GetOutcomeArgs  []byte                 `protobuf:"bytes,4,opt,name=get_outcome_args,json=getOutcomeArgs,proto3" json:"get_outcome_args,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_web_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{11}
}

func (x *Condition) GetOnChainDeployed() bool {
	if x != nil {
		return x.OnChainDeployed
	}
	return false
}

func (x *Condition) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *Condition) GetIsFinalizedArgs() []byte {
	if x != nil {
		return x.IsFinalizedArgs
	}
	return nil
}

func (x *Condition) GetGetOutcomeArgs() []byte {
	if x != nil {
		return x.GetOutcomeArgs
	}
	return nil
}

type SendConditionalPaymentRequest struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	TokenInfo         *TokenInfo                  `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	Amount            string                      `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Destination       string                      `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	TransferLogicType entity.TransferFunctionType `protobuf:"varint,4,opt,name=transfer_logic_type,json=transferLogicType,proto3,enum=entity.TransferFunctionType" json:"transfer_logic_type,omitempty"`
	// Empty conditions means the caller is not supplying any app-level conditions.
	// The runtime may still prepend an internal hash-lock condition for non-direct pays.
	Conditions    []*Condition `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Timeout       uint64       `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Note          *anypb.Any   `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendConditionalPaymentRequest) Reset() {
	*x = SendConditionalPaymentRequest{}
	mi := &file_web_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendConditionalPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendConditionalPaymentRequest) ProtoMessage() {}

func (x *SendConditionalPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendConditionalPaymentRequest.ProtoReflect.Descriptor instead.
func (*SendConditionalPaymentRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{12}
}

func (x *SendConditionalPaymentRequest) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *SendConditionalPaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendConditionalPaymentRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SendConditionalPaymentRequest) GetTransferLogicType() entity.TransferFunctionType {
	if x != nil {
		return x.TransferLogicType
	}
	return entity.TransferFunctionType(0)
}

func (x *SendConditionalPaymentRequest) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *SendConditionalPaymentRequest) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *SendConditionalPaymentRequest) GetNote() *anypb.Any {
	if x != nil {
		return x.Note
	}
	return nil
}

type SendTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenInfo     *TokenInfo             `protobuf:"bytes,1,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Note          *anypb.Any             `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTokenRequest) Reset() {
	*x = SendTokenRequest{}
	mi := &file_web_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTokenRequest) ProtoMessage() {}

func (x *SendTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTokenRequest.ProtoReflect.Descriptor instead.
func (*SendTokenRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{13}
}

func (x *SendTokenRequest) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *SendTokenRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *SendTokenRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SendTokenRequest) GetNote() *anypb.Any {
	if x != nil {
		return x.Note
	}
	return nil
}

type PaymentID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentID) Reset() {
	*x = PaymentID{}
	mi := &file_web_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentID) ProtoMessage() {}

func (x *PaymentID) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentID.ProtoReflect.Descriptor instead.
func (*PaymentID) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{14}
}

func (x *PaymentID) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type PaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	TokenInfo     *TokenInfo             `protobuf:"bytes,4,opt,name=token_info,json=tokenInfo,proto3" json:"token_info,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentJson   string                 `protobuf:"bytes,6,opt,name=payment_json,json=paymentJson,proto3" json:"payment_json,omitempty"`
	Status        uint32                 `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentInfo) Reset() {
	*x = PaymentInfo{}
	mi := &file_web_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentInfo) ProtoMessage() {}

func (x *PaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentInfo.ProtoReflect.Descriptor instead.
func (*PaymentInfo) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{15}
}

func (x *PaymentInfo) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PaymentInfo) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *PaymentInfo) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *PaymentInfo) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *PaymentInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *PaymentInfo) GetPaymentJson() string {
	if x != nil {
		return x.PaymentJson
	}
	return ""
}

func (x *PaymentInfo) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type OutgoingPaymentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *PaymentInfo           `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	ErrorCode     int64                  `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingPaymentInfo) Reset() {
	*x = OutgoingPaymentInfo{}
	mi := &file_web_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingPaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingPaymentInfo) ProtoMessage() {}

func (x *OutgoingPaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingPaymentInfo.ProtoReflect.Descriptor instead.
func (*OutgoingPaymentInfo) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{16}
}

func (x *OutgoingPaymentInfo) GetPayment() *PaymentInfo {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *OutgoingPaymentInfo) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *OutgoingPaymentInfo) GetErrorCode() int64 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

type OnChainPaymentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Amount          string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ResolveDeadline uint64                 `protobuf:"varint,2,opt,name=resolve_deadline,json=resolveDeadline,proto3" json:"resolve_deadline,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnChainPaymentInfo) Reset() {
	*x = OnChainPaymentInfo{}
	mi := &file_web_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnChainPaymentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnChainPaymentInfo) ProtoMessage() {}

func (x *OnChainPaymentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnChainPaymentInfo.ProtoReflect.Descriptor instead.
func (*OnChainPaymentInfo) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{17}
}

func (x *OnChainPaymentInfo) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OnChainPaymentInfo) GetResolveDeadline() uint64 {
	if x != nil {
		return x.ResolveDeadline
	}
	return 0
}

type SessionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionID) Reset() {
	*x = SessionID{}
	mi := &file_web_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionID) ProtoMessage() {}

func (x *SessionID) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionID.ProtoReflect.Descriptor instead.
func (*SessionID) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{18}
}

func (x *SessionID) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateAppSessionOnVirtualContractRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ContractBin         string                 `protobuf:"bytes,1,opt,name=contract_bin,json=contractBin,proto3" json:"contract_bin,omitempty"`
	ContractConstructor string                 `protobuf:"bytes,2,opt,name=contract_constructor,json=contractConstructor,proto3" json:"contract_constructor,omitempty"`
	Nonce               uint64                 `protobuf:"varint,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	OnChainTimeout      uint64                 `protobuf:"varint,4,opt,name=on_chain_timeout,json=onChainTimeout,proto3" json:"on_chain_timeout,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateAppSessionOnVirtualContractRequest) Reset() {
	*x = CreateAppSessionOnVirtualContractRequest{}
	mi := &file_web_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppSessionOnVirtualContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppSessionOnVirtualContractRequest) ProtoMessage() {}

func (x *CreateAppSessionOnVirtualContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppSessionOnVirtualContractRequest.ProtoReflect.Descriptor instead.
func (*CreateAppSessionOnVirtualContractRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{19}
}

func (x *CreateAppSessionOnVirtualContractRequest) GetContractBin() string {
	if x != nil {
		return x.ContractBin
	}
	return ""
}

func (x *CreateAppSessionOnVirtualContractRequest) GetContractConstructor() string {
	if x != nil {
		return x.ContractConstructor
	}
	return ""
}

func (x *CreateAppSessionOnVirtualContractRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *CreateAppSessionOnVirtualContractRequest) GetOnChainTimeout() uint64 {
	if x != nil {
		return x.OnChainTimeout
	}
	return 0
}

type CreateAppSessionOnDeployedContractRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Nonce           uint64                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	OnChainTimeout  uint64                 `protobuf:"varint,3,opt,name=on_chain_timeout,json=onChainTimeout,proto3" json:"on_chain_timeout,omitempty"`
	Participants    []string               `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAppSessionOnDeployedContractRequest) Reset() {
	*x = CreateAppSessionOnDeployedContractRequest{}
	mi := &file_web_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppSessionOnDeployedContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppSessionOnDeployedContractRequest) ProtoMessage() {}

func (x *CreateAppSessionOnDeployedContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppSessionOnDeployedContractRequest.ProtoReflect.Descriptor instead.
func (*CreateAppSessionOnDeployedContractRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{20}
}

func (x *CreateAppSessionOnDeployedContractRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *CreateAppSessionOnDeployedContractRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *CreateAppSessionOnDeployedContractRequest) GetOnChainTimeout() uint64 {
	if x != nil {
		return x.OnChainTimeout
	}
	return 0
}

func (x *CreateAppSessionOnDeployedContractRequest) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type DisputeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SeqNum        uint64                 `protobuf:"varint,2,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisputeInfo) Reset() {
	*x = DisputeInfo{}
	mi := &file_web_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisputeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisputeInfo) ProtoMessage() {}

func (x *DisputeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisputeInfo.ProtoReflect.Descriptor instead.
func (*DisputeInfo) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{21}
}

func (x *DisputeInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DisputeInfo) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type SignOutgoingStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         []byte                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutgoingStateRequest) Reset() {
	*x = SignOutgoingStateRequest{}
	mi := &file_web_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutgoingStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutgoingStateRequest) ProtoMessage() {}

func (x *SignOutgoingStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutgoingStateRequest.ProtoReflect.Descriptor instead.
func (*SignOutgoingStateRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{22}
}

func (x *SignOutgoingStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignOutgoingStateRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type SignedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignedState   []byte                 `protobuf:"bytes,1,opt,name=signed_state,json=signedState,proto3" json:"signed_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedState) Reset() {
	*x = SignedState{}
	mi := &file_web_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedState) ProtoMessage() {}

func (x *SignedState) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedState.ProtoReflect.Descriptor instead.
func (*SignedState) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{23}
}

func (x *SignedState) GetSignedState() []byte {
	if x != nil {
		return x.SignedState
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_web_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{24}
}

func (x *Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_web_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{25}
}

func (x *Signature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ValidateAckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Envelope      []byte                 `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAckRequest) Reset() {
	*x = ValidateAckRequest{}
	mi := &file_web_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAckRequest) ProtoMessage() {}

func (x *ValidateAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAckRequest.ProtoReflect.Descriptor instead.
func (*ValidateAckRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{26}
}

func (x *ValidateAckRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidateAckRequest) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type BoolValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolValue) Reset() {
	*x = BoolValue{}
	mi := &file_web_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolValue) ProtoMessage() {}

func (x *BoolValue) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolValue.ProtoReflect.Descriptor instead.
func (*BoolValue) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{27}
}

func (x *BoolValue) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ProcessReceivedStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Envelope      []byte                 `protobuf:"bytes,2,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReceivedStateRequest) Reset() {
	*x = ProcessReceivedStateRequest{}
	mi := &file_web_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReceivedStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReceivedStateRequest) ProtoMessage() {}

func (x *ProcessReceivedStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReceivedStateRequest.ProtoReflect.Descriptor instead.
func (*ProcessReceivedStateRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{28}
}

func (x *ProcessReceivedStateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProcessReceivedStateRequest) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type ProcessReceivedStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecodedState  []byte                 `protobuf:"bytes,1,opt,name=decoded_state,json=decodedState,proto3" json:"decoded_state,omitempty"`
	PreparedAck   []byte                 `protobuf:"bytes,2,opt,name=prepared_ack,json=preparedAck,proto3" json:"prepared_ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessReceivedStateResponse) Reset() {
	*x = ProcessReceivedStateResponse{}
	mi := &file_web_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessReceivedStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessReceivedStateResponse) ProtoMessage() {}

func (x *ProcessReceivedStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessReceivedStateResponse.ProtoReflect.Descriptor instead.
func (*ProcessReceivedStateResponse) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{29}
}

func (x *ProcessReceivedStateResponse) GetDecodedState() []byte {
	if x != nil {
		return x.DecodedState
	}
	return nil
}

func (x *ProcessReceivedStateResponse) GetPreparedAck() []byte {
	if x != nil {
		return x.PreparedAck
	}
	return nil
}

type SettleAppSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StateProof    []byte                 `protobuf:"bytes,2,opt,name=state_proof,json=stateProof,proto3" json:"state_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleAppSessionRequest) Reset() {
	*x = SettleAppSessionRequest{}
	mi := &file_web_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleAppSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleAppSessionRequest) ProtoMessage() {}

func (x *SettleAppSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleAppSessionRequest.ProtoReflect.Descriptor instead.
func (*SettleAppSessionRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{30}
}

func (x *SettleAppSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SettleAppSessionRequest) GetStateProof() []byte {
	if x != nil {
		return x.StateProof
	}
	return nil
}

type SettleAppSessionByTimeoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OracleProof   []byte                 `protobuf:"bytes,2,opt,name=oracle_proof,json=oracleProof,proto3" json:"oracle_proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleAppSessionByTimeoutRequest) Reset() {
	*x = SettleAppSessionByTimeoutRequest{}
	mi := &file_web_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleAppSessionByTimeoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleAppSessionByTimeoutRequest) ProtoMessage() {}

func (x *SettleAppSessionByTimeoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleAppSessionByTimeoutRequest.ProtoReflect.Descriptor instead.
func (*SettleAppSessionByTimeoutRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{31}
}

func (x *SettleAppSessionByTimeoutRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SettleAppSessionByTimeoutRequest) GetOracleProof() []byte {
	if x != nil {
		return x.OracleProof
	}
	return nil
}

type SettleAppSessionByInvalidityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OracleProof        []byte                 `protobuf:"bytes,2,opt,name=oracle_proof,json=oracleProof,proto3" json:"oracle_proof,omitempty"`
	CosignedStateProof []byte                 `protobuf:"bytes,3,opt,name=cosigned_state_proof,json=cosignedStateProof,proto3" json:"cosigned_state_proof,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SettleAppSessionByInvalidityRequest) Reset() {
	*x = SettleAppSessionByInvalidityRequest{}
	mi := &file_web_api_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleAppSessionByInvalidityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleAppSessionByInvalidityRequest) ProtoMessage() {}

func (x *SettleAppSessionByInvalidityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleAppSessionByInvalidityRequest.ProtoReflect.Descriptor instead.
func (*SettleAppSessionByInvalidityRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{32}
}

func (x *SettleAppSessionByInvalidityRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SettleAppSessionByInvalidityRequest) GetOracleProof() []byte {
	if x != nil {
		return x.OracleProof
	}
	return nil
}

func (x *SettleAppSessionByInvalidityRequest) GetCosignedStateProof() []byte {
	if x != nil {
		return x.CosignedStateProof
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_web_api_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{33}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBooleanOutcomeForAppSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Query         []byte                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooleanOutcomeForAppSessionRequest) Reset() {
	*x = GetBooleanOutcomeForAppSessionRequest{}
	mi := &file_web_api_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooleanOutcomeForAppSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooleanOutcomeForAppSessionRequest) ProtoMessage() {}

func (x *GetBooleanOutcomeForAppSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooleanOutcomeForAppSessionRequest.ProtoReflect.Descriptor instead.
func (*GetBooleanOutcomeForAppSessionRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{34}
}

func (x *GetBooleanOutcomeForAppSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetBooleanOutcomeForAppSessionRequest) GetQuery() []byte {
	if x != nil {
		return x.Query
	}
	return nil
}

type BooleanOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finalized     bool                   `protobuf:"varint,1,opt,name=finalized,proto3" json:"finalized,omitempty"`
	Outcome       bool                   `protobuf:"varint,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BooleanOutcome) Reset() {
	*x = BooleanOutcome{}
	mi := &file_web_api_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BooleanOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanOutcome) ProtoMessage() {}

func (x *BooleanOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanOutcome.ProtoReflect.Descriptor instead.
func (*BooleanOutcome) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{35}
}

func (x *BooleanOutcome) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *BooleanOutcome) GetOutcome() bool {
	if x != nil {
		return x.Outcome
	}
	return false
}

type ApplyActionForAppSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Action        []byte                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyActionForAppSessionRequest) Reset() {
	*x = ApplyActionForAppSessionRequest{}
	mi := &file_web_api_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyActionForAppSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyActionForAppSessionRequest) ProtoMessage() {}

func (x *ApplyActionForAppSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyActionForAppSessionRequest.ProtoReflect.Descriptor instead.
func (*ApplyActionForAppSessionRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{36}
}

func (x *ApplyActionForAppSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ApplyActionForAppSessionRequest) GetAction() []byte {
	if x != nil {
		return x.Action
	}
	return nil
}

type BlockNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockNumber) Reset() {
	*x = BlockNumber{}
	mi := &file_web_api_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockNumber) ProtoMessage() {}

func (x *BlockNumber) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockNumber.ProtoReflect.Descriptor instead.
func (*BlockNumber) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{37}
}

func (x *BlockNumber) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type AppSessionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSessionStatus) Reset() {
	*x = AppSessionStatus{}
	mi := &file_web_api_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSessionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSessionStatus) ProtoMessage() {}

func (x *AppSessionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSessionStatus.ProtoReflect.Descriptor instead.
func (*AppSessionStatus) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{38}
}

func (x *AppSessionStatus) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetStateForAppSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Key           int64                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateForAppSessionRequest) Reset() {
	*x = GetStateForAppSessionRequest{}
	mi := &file_web_api_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateForAppSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateForAppSessionRequest) ProtoMessage() {}

func (x *GetStateForAppSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateForAppSessionRequest.ProtoReflect.Descriptor instead.
func (*GetStateForAppSessionRequest) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{39}
}

func (x *GetStateForAppSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStateForAppSessionRequest) GetKey() int64 {
	if x != nil {
		return x.Key
	}
	return 0
}

type AppSessionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []byte                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSessionState) Reset() {
	*x = AppSessionState{}
	mi := &file_web_api_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSessionState) ProtoMessage() {}

func (x *AppSessionState) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSessionState.ProtoReflect.Descriptor instead.
func (*AppSessionState) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{40}
}

func (x *AppSessionState) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

type AppSessionSeqNum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        uint64                 `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppSessionSeqNum) Reset() {
	*x = AppSessionSeqNum{}
	mi := &file_web_api_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSessionSeqNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSessionSeqNum) ProtoMessage() {}

func (x *AppSessionSeqNum) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSessionSeqNum.ProtoReflect.Descriptor instead.
func (*AppSessionSeqNum) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{41}
}

func (x *AppSessionSeqNum) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type SetMsgDropReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DropRecv      bool                   `protobuf:"varint,1,opt,name=drop_recv,json=dropRecv,proto3" json:"drop_recv,omitempty"`
	DropSend      bool                   `protobuf:"varint,2,opt,name=drop_send,json=dropSend,proto3" json:"drop_send,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMsgDropReq) Reset() {
	*x = SetMsgDropReq{}
	mi := &file_web_api_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMsgDropReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMsgDropReq) ProtoMessage() {}

func (x *SetMsgDropReq) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMsgDropReq.ProtoReflect.Descriptor instead.
func (*SetMsgDropReq) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{42}
}

func (x *SetMsgDropReq) GetDropRecv() bool {
	if x != nil {
		return x.DropRecv
	}
	return false
}

func (x *SetMsgDropReq) GetDropSend() bool {
	if x != nil {
		return x.DropSend
	}
	return false
}

type PaymentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        uint32                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentStatus) Reset() {
	*x = PaymentStatus{}
	mi := &file_web_api_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentStatus) ProtoMessage() {}

func (x *PaymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_web_api_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentStatus.ProtoReflect.Descriptor instead.
func (*PaymentStatus) Descriptor() ([]byte, []int) {
	return file_web_api_proto_rawDescGZIP(), []int{43}
}

func (x *PaymentStatus) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_web_api_proto protoreflect.FileDescriptor

const file_web_api_proto_rawDesc = "" +
	"\n" +
	"\rweb_api.proto\x12\x06webrpc\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\fentity.proto\x1a\rmessage.proto\"Y\n" +
	"\x14GetPayHistoryRequest\x12\x1d\n" +
	"\n" +
	"from_start\x18\x01 \x01(\bR\tfromStart\x12\"\n" +
	"\fitemsPerPage\x18\x02 \x01(\x05R\fitemsPerPage\"j\n" +
	"\x15GetPayHistoryResponse\x12)\n" +
	"\x04pays\x18\x01 \x03(\v2\x15.rpc.OneHistoricalPayR\x04pays\x12&\n" +
	"\x0fhas_more_result\x18\x02 \x01(\bR\rhasMoreResult\"b\n" +
	"\tTokenInfo\x120\n" +
	"\n" +
	"token_type\x18\x01 \x01(\x0e2\x11.entity.TokenTypeR\ttokenType\x12#\n" +
	"\rtoken_address\x18\x02 \x01(\tR\ftokenAddress\"q\n" +
	"\x14SetDelegationRequest\x122\n" +
	"\vtoken_infos\x18\x01 \x03(\v2\x11.webrpc.TokenInfoR\n" +
	"tokenInfos\x12%\n" +
	"\x0eblock_duration\x18\x02 \x01(\x03R\rblockDuration\"\x86\x01\n" +
	"\x19OpenPaymentChannelRequest\x120\n" +
	"\n" +
	"token_info\x18\x01 \x01(\v2\x11.webrpc.TokenInfoR\ttokenInfo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1f\n" +
	"\vpeer_amount\x18\x03 \x01(\tR\n" +
	"peerAmount\"*\n" +
	"\tChannelID\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\"d\n" +
	"\x18DepositOrWithdrawRequest\x120\n" +
	"\n" +
	"token_info\x18\x01 \x01(\v2\x11.webrpc.TokenInfoR\ttokenInfo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"F\n" +
	"\x14DepositOrWithdrawJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\"\x8d\x01\n" +
	"\x12GetBalanceResponse\x12!\n" +
	"\ffree_balance\x18\x01 \x01(\tR\vfreeBalance\x12%\n" +
	"\x0elocked_balance\x18\x02 \x01(\tR\rlockedBalance\x12-\n" +
	"\x12receiving_capacity\x18\x03 \x01(\tR\x11receivingCapacity\"p\n" +
	"\x19GetPeerFreeBalanceRequest\x120\n" +
	"\n" +
	"token_info\x18\x01 \x01(\v2\x11.webrpc.TokenInfoR\ttokenInfo\x12!\n" +
	"\fpeer_address\x18\x02 \x01(\tR\vpeerAddress\"Q\n" +
	"\vFreeBalance\x12!\n" +
	"\ffree_balance\x18\x01 \x01(\tR\vfreeBalance\x12\x1f\n" +
	"\vjoin_status\x18\x02 \x01(\x05R\n" +
	"joinStatus\"\xb8\x01\n" +
	"\tCondition\x12*\n" +
	"\x11on_chain_deployed\x18\x01 \x01(\bR\x0fonChainDeployed\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\x12*\n" +
	"\x11is_finalized_args\x18\x03 \x01(\fR\x0fisFinalizedArgs\x12(\n" +
	"\x10get_outcome_args\x18\x04 \x01(\fR\x0egetOutcomeArgs\"\xd0\x02\n" +
	"\x1dSendConditionalPaymentRequest\x120\n" +
	"\n" +
	"token_info\x18\x01 \x01(\v2\x11.webrpc.TokenInfoR\ttokenInfo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12L\n" +
	"\x13transfer_logic_type\x18\x04 \x01(\x0e2\x1c.entity.TransferFunctionTypeR\x11transferLogicType\x121\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x11.webrpc.ConditionR\n" +
	"conditions\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x04R\atimeout\x12(\n" +
	"\x04note\x18\a \x01(\v2\x14.google.protobuf.AnyR\x04note\"\xa8\x01\n" +
	"\x10SendTokenRequest\x120\n" +
	"\n" +
	"token_info\x18\x01 \x01(\v2\x11.webrpc.TokenInfoR\ttokenInfo\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12(\n" +
	"\x04note\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\x04note\"*\n" +
	"\tPaymentID\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xe5\x01\n" +
	"\vPaymentInfo\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x03 \x01(\tR\breceiver\x120\n" +
	"\n" +
	"token_info\x18\x04 \x01(\v2\x11.webrpc.TokenInfoR\ttokenInfo\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12!\n" +
	"\fpayment_json\x18\x06 \x01(\tR\vpaymentJson\x12\x16\n" +
	"\x06status\x18\a \x01(\rR\x06status\"\x86\x01\n" +
	"\x13OutgoingPaymentInfo\x12-\n" +
	"\apayment\x18\x01 \x01(\v2\x13.webrpc.PaymentInfoR\apayment\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x03R\terrorCode\"W\n" +
	"\x12OnChainPaymentInfo\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12)\n" +
	"\x10resolve_deadline\x18\x02 \x01(\x04R\x0fresolveDeadline\"*\n" +
	"\tSessionID\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xc0\x01\n" +
	"(CreateAppSessionOnVirtualContractRequest\x12!\n" +
	"\fcontract_bin\x18\x01 \x01(\tR\vcontractBin\x121\n" +
	"\x14contract_constructor\x18\x02 \x01(\tR\x13contractConstructor\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\x04R\x05nonce\x12(\n" +
	"\x10on_chain_timeout\x18\x04 \x01(\x04R\x0eonChainTimeout\"\xba\x01\n" +
	")CreateAppSessionOnDeployedContractRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12(\n" +
	"\x10on_chain_timeout\x18\x03 \x01(\x04R\x0eonChainTimeout\x12\"\n" +
	"\fparticipants\x18\x04 \x03(\tR\fparticipants\"E\n" +
	"\vDisputeInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aseq_num\x18\x02 \x01(\x04R\x06seqNum\"O\n" +
	"\x18SignOutgoingStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05state\"0\n" +
	"\vSignedState\x12!\n" +
	"\fsigned_state\x18\x01 \x01(\fR\vsignedState\"\x1a\n" +
	"\x04Data\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\tSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\"O\n" +
	"\x12ValidateAckRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\benvelope\x18\x02 \x01(\fR\benvelope\"!\n" +
	"\tBoolValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"X\n" +
	"\x1bProcessReceivedStateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\benvelope\x18\x02 \x01(\fR\benvelope\"f\n" +
	"\x1cProcessReceivedStateResponse\x12#\n" +
	"\rdecoded_state\x18\x01 \x01(\fR\fdecodedState\x12!\n" +
	"\fprepared_ack\x18\x02 \x01(\fR\vpreparedAck\"Y\n" +
	"\x17SettleAppSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vstate_proof\x18\x02 \x01(\fR\n" +
	"stateProof\"d\n" +
	" SettleAppSessionByTimeoutRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foracle_proof\x18\x02 \x01(\fR\voracleProof\"\x99\x01\n" +
	"#SettleAppSessionByInvalidityRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\foracle_proof\x18\x02 \x01(\fR\voracleProof\x120\n" +
	"\x14cosigned_state_proof\x18\x03 \x01(\fR\x12cosignedStateProof\"#\n" +
	"\aAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\\\n" +
	"%GetBooleanOutcomeForAppSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\fR\x05query\"H\n" +
	"\x0eBooleanOutcome\x12\x1c\n" +
	"\tfinalized\x18\x01 \x01(\bR\tfinalized\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\bR\aoutcome\"X\n" +
	"\x1fApplyActionForAppSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\fR\x06action\"0\n" +
	"\vBlockNumber\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"*\n" +
	"\x10AppSessionStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\"O\n" +
	"\x1cGetStateForAppSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x03R\x03key\"'\n" +
	"\x0fAppSessionState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\fR\x05state\"+\n" +
	"\x10AppSessionSeqNum\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x04R\x06seqNum\"I\n" +
	"\rSetMsgDropReq\x12\x1b\n" +
	"\tdrop_recv\x18\x01 \x01(\bR\bdropRecv\x12\x1b\n" +
	"\tdrop_send\x18\x02 \x01(\bR\bdropSend\"'\n" +
	"\rPaymentStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status2\xdc\"\n" +
	"\x06WebApi\x12N\n" +
	"\rGetPayHistory\x12\x1c.webrpc.GetPayHistoryRequest\x1a\x1d.webrpc.GetPayHistoryResponse\"\x00\x12G\n" +
	"\rSetDelegation\x12\x1c.webrpc.SetDelegationRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x12OpenPaymentChannel\x12!.webrpc.OpenPaymentChannelRequest\x1a\x11.webrpc.ChannelID\"\x00\x12K\n" +
	"\aDeposit\x12 .webrpc.DepositOrWithdrawRequest\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12V\n" +
	"\x12DepositNonBlocking\x12 .webrpc.DepositOrWithdrawRequest\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12Q\n" +
	"\x11MonitorDepositJob\x12\x1c.webrpc.DepositOrWithdrawJob\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12W\n" +
	"\x13CooperativeWithdraw\x12 .webrpc.DepositOrWithdrawRequest\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12b\n" +
	"\x1eCooperativeWithdrawNonBlocking\x12 .webrpc.DepositOrWithdrawRequest\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12]\n" +
	"\x1dMonitorCooperativeWithdrawJob\x12\x1c.webrpc.DepositOrWithdrawJob\x1a\x1c.webrpc.DepositOrWithdrawJob\"\x00\x12=\n" +
	"\n" +
	"GetBalance\x12\x11.webrpc.TokenInfo\x1a\x1a.webrpc.GetBalanceResponse\"\x00\x12N\n" +
	"\x12GetPeerFreeBalance\x12!.webrpc.GetPeerFreeBalanceRequest\x1a\x13.webrpc.FreeBalance\"\x00\x12:\n" +
	"\tSendToken\x12\x18.webrpc.SendTokenRequest\x1a\x11.webrpc.PaymentID\"\x00\x12T\n" +
	"\x16SendConditionalPayment\x12%.webrpc.SendConditionalPaymentRequest\x1a\x11.webrpc.PaymentID\"\x00\x12L\n" +
	"\x19SubscribeIncomingPayments\x12\x16.google.protobuf.Empty\x1a\x13.webrpc.PaymentInfo\"\x000\x01\x12T\n" +
	"\x19SubscribeOutgoingPayments\x12\x16.google.protobuf.Empty\x1a\x1b.webrpc.OutgoingPaymentInfo\"\x000\x01\x12F\n" +
	"\x18GetIncomingPaymentStatus\x12\x11.webrpc.PaymentID\x1a\x15.webrpc.PaymentStatus\"\x00\x12F\n" +
	"\x18GetOutgoingPaymentStatus\x12\x11.webrpc.PaymentID\x1a\x15.webrpc.PaymentStatus\"\x00\x12E\n" +
	"\x16ConfirmOutgoingPayment\x12\x11.webrpc.PaymentID\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x15RejectIncomingPayment\x12\x11.webrpc.PaymentID\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"$SettleOnChainResolvedIncomingPayment\x12\x11.webrpc.PaymentID\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x1dResolveIncomingPaymentOnChain\x12\x11.webrpc.PaymentID\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x15GetOnChainPaymentInfo\x12\x11.webrpc.PaymentID\x1a\x1a.webrpc.OnChainPaymentInfo\"\x00\x12M\n" +
	"\x1eConfirmOnChainResolvedPayments\x12\x11.webrpc.TokenInfo\x1a\x16.google.protobuf.Empty\"\x00\x12D\n" +
	"\x15SettleExpiredPayments\x12\x11.webrpc.TokenInfo\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eIntendWithdraw\x12 .webrpc.DepositOrWithdrawRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\x0fConfirmWithdraw\x12\x11.webrpc.TokenInfo\x1a\x16.google.protobuf.Empty\"\x00\x12I\n" +
	"\x1aIntendSettlePaymentChannel\x12\x11.webrpc.TokenInfo\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x1bConfirmSettlePaymentChannel\x12\x11.webrpc.TokenInfo\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"'GetSettleFinalizedTimeForPaymentChannel\x12\x11.webrpc.TokenInfo\x1a\x13.webrpc.BlockNumber\"\x00\x12N\n" +
	"\x1fSyncOnChainPaymentChannelStatus\x12\x11.webrpc.TokenInfo\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\x11SyncStateWithPeer\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12j\n" +
	"!CreateAppSessionOnVirtualContract\x120.webrpc.CreateAppSessionOnVirtualContractRequest\x1a\x11.webrpc.SessionID\"\x00\x12l\n" +
	"\"CreateAppSessionOnDeployedContract\x121.webrpc.CreateAppSessionOnDeployedContractRequest\x1a\x11.webrpc.SessionID\"\x00\x12H\n" +
	"\x1aSubscribeAppSessionDispute\x12\x11.webrpc.SessionID\x1a\x13.webrpc.DisputeInfo\"\x000\x01\x12L\n" +
	"\x11SignOutgoingState\x12 .webrpc.SignOutgoingStateRequest\x1a\x13.webrpc.SignedState\"\x00\x12>\n" +
	"\vValidateAck\x12\x1a.webrpc.ValidateAckRequest\x1a\x11.webrpc.BoolValue\"\x00\x12-\n" +
	"\bSignData\x12\f.webrpc.Data\x1a\x11.webrpc.Signature\"\x00\x12c\n" +
	"\x14ProcessReceivedState\x12#.webrpc.ProcessReceivedStateRequest\x1a$.webrpc.ProcessReceivedStateResponse\"\x00\x12M\n" +
	"\x10SettleAppSession\x12\x1f.webrpc.SettleAppSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12b\n" +
	"\x1cSettleAppSessionBySigTimeout\x12(.webrpc.SettleAppSessionByTimeoutRequest\x1a\x16.google.protobuf.Empty\"\x00\x12c\n" +
	"\x1dSettleAppSessionByMoveTimeout\x12(.webrpc.SettleAppSessionByTimeoutRequest\x1a\x16.google.protobuf.Empty\"\x00\x12f\n" +
	"\x1dSettleAppSessionByInvalidTurn\x12+.webrpc.SettleAppSessionByInvalidityRequest\x1a\x16.google.protobuf.Empty\"\x00\x12g\n" +
	"\x1eSettleAppSessionByInvalidState\x12+.webrpc.SettleAppSessionByInvalidityRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\x10DeleteAppSession\x12\x11.webrpc.SessionID\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\x1fGetDeployedAddressForAppSession\x12\x11.webrpc.SessionID\x1a\x0f.webrpc.Address\"\x00\x12i\n" +
	"\x1eGetBooleanOutcomeForAppSession\x12-.webrpc.GetBooleanOutcomeForAppSessionRequest\x1a\x16.webrpc.BooleanOutcome\"\x00\x12]\n" +
	"\x18ApplyActionForAppSession\x12'.webrpc.ApplyActionForAppSessionRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"$FinalizeOnActionTimeoutForAppSession\x12\x11.webrpc.SessionID\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"#GetSettleFinalizedTimeForAppSession\x12\x11.webrpc.SessionID\x1a\x13.webrpc.BlockNumber\"\x00\x12J\n" +
	"\x1eGetActionDeadlineForAppSession\x12\x11.webrpc.SessionID\x1a\x13.webrpc.BlockNumber\"\x00\x12G\n" +
	"\x16GetStatusForAppSession\x12\x11.webrpc.SessionID\x1a\x18.webrpc.AppSessionStatus\"\x00\x12X\n" +
	"\x15GetStateForAppSession\x12$.webrpc.GetStateForAppSessionRequest\x1a\x17.webrpc.AppSessionState\"\x00\x12G\n" +
	"\x16GetSeqNumForAppSession\x12\x11.webrpc.SessionID\x1a\x18.webrpc.AppSessionSeqNum\"\x00\x12?\n" +
	"\x0eGetBlockNumber\x12\x16.google.protobuf.Empty\x1a\x13.webrpc.BlockNumber\"\x00\x12@\n" +
	"\rSetMsgDropper\x12\x15.webrpc.SetMsgDropReq\x1a\x16.google.protobuf.Empty\"\x00B/Z-github.com/celer-network/agent-pay/webapi/rpcb\x06proto3"

var (
	file_web_api_proto_rawDescOnce sync.Once
	file_web_api_proto_rawDescData []byte
)

func file_web_api_proto_rawDescGZIP() []byte {
	file_web_api_proto_rawDescOnce.Do(func() {
		file_web_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_api_proto_rawDesc), len(file_web_api_proto_rawDesc)))
	})
	return file_web_api_proto_rawDescData
}

var file_web_api_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_web_api_proto_goTypes = []any{
	(*GetPayHistoryRequest)(nil),                      // 0: webrpc.GetPayHistoryRequest
	(*GetPayHistoryResponse)(nil),                     // 1: webrpc.GetPayHistoryResponse
	(*TokenInfo)(nil),                                 // 2: webrpc.TokenInfo
	(*SetDelegationRequest)(nil),                      // 3: webrpc.SetDelegationRequest
	(*OpenPaymentChannelRequest)(nil),                 // 4: webrpc.OpenPaymentChannelRequest
	(*ChannelID)(nil),                                 // 5: webrpc.ChannelID
	(*DepositOrWithdrawRequest)(nil),                  // 6: webrpc.DepositOrWithdrawRequest
	(*DepositOrWithdrawJob)(nil),                      // 7: webrpc.DepositOrWithdrawJob
	(*GetBalanceResponse)(nil),                        // 8: webrpc.GetBalanceResponse
	(*GetPeerFreeBalanceRequest)(nil),                 // 9: webrpc.GetPeerFreeBalanceRequest
	(*FreeBalance)(nil),                               // 10: webrpc.FreeBalance
	(*Condition)(nil),                                 // 11: webrpc.Condition
	(*SendConditionalPaymentRequest)(nil),             // 12: webrpc.SendConditionalPaymentRequest
	(*SendTokenRequest)(nil),                          // 13: webrpc.SendTokenRequest
	(*PaymentID)(nil),                                 // 14: webrpc.PaymentID
	(*PaymentInfo)(nil),                               // 15: webrpc.PaymentInfo
	(*OutgoingPaymentInfo)(nil),                       // 16: webrpc.OutgoingPaymentInfo
	(*OnChainPaymentInfo)(nil),                        // 17: webrpc.OnChainPaymentInfo
	(*SessionID)(nil),                                 // 18: webrpc.SessionID
	(*CreateAppSessionOnVirtualContractRequest)(nil),  // 19: webrpc.CreateAppSessionOnVirtualContractRequest
	(*CreateAppSessionOnDeployedContractRequest)(nil), // 20: webrpc.CreateAppSessionOnDeployedContractRequest
	(*DisputeInfo)(nil),                               // 21: webrpc.DisputeInfo
	(*SignOutgoingStateRequest)(nil),                  // 22: webrpc.SignOutgoingStateRequest
	(*SignedState)(nil),                               // 23: webrpc.SignedState
	(*Data)(nil),                                      // 24: webrpc.Data
	(*Signature)(nil),                                 // 25: webrpc.Signature
	(*ValidateAckRequest)(nil),                        // 26: webrpc.ValidateAckRequest
	(*BoolValue)(nil),                                 // 27: webrpc.BoolValue
	(*ProcessReceivedStateRequest)(nil),               // 28: webrpc.ProcessReceivedStateRequest
	(*ProcessReceivedStateResponse)(nil),              // 29: webrpc.ProcessReceivedStateResponse
	(*SettleAppSessionRequest)(nil),                   // 30: webrpc.SettleAppSessionRequest
	(*SettleAppSessionByTimeoutRequest)(nil),          // 31: webrpc.SettleAppSessionByTimeoutRequest
	(*SettleAppSessionByInvalidityRequest)(nil),       // 32: webrpc.SettleAppSessionByInvalidityRequest
	(*Address)(nil),                                   // 33: webrpc.Address
	(*GetBooleanOutcomeForAppSessionRequest)(nil),     // 34: webrpc.GetBooleanOutcomeForAppSessionRequest
	(*BooleanOutcome)(nil),                            // 35: webrpc.BooleanOutcome
	(*ApplyActionForAppSessionRequest)(nil),           // 36: webrpc.ApplyActionForAppSessionRequest
	(*BlockNumber)(nil),                               // 37: webrpc.BlockNumber
	(*AppSessionStatus)(nil),                          // 38: webrpc.AppSessionStatus
	(*GetStateForAppSessionRequest)(nil),              // 39: webrpc.GetStateForAppSessionRequest
	(*AppSessionState)(nil),                           // 40: webrpc.AppSessionState
	(*AppSessionSeqNum)(nil),                          // 41: webrpc.AppSessionSeqNum
	(*SetMsgDropReq)(nil),                             // 42: webrpc.SetMsgDropReq
	(*PaymentStatus)(nil),                             // 43: webrpc.PaymentStatus
	(*rpc.OneHistoricalPay)(nil),                      // 44: rpc.OneHistoricalPay
	(entity.TokenType)(0),                             // 45: entity.TokenType
	(entity.TransferFunctionType)(0),                  // 46: entity.TransferFunctionType
	(*anypb.Any)(nil),                                 // 47: google.protobuf.Any
	(*emptypb.Empty)(nil),                             // 48: google.protobuf.Empty
}
var file_web_api_proto_depIdxs = []int32{
	44, // 0: webrpc.GetPayHistoryResponse.pays:type_name -> rpc.OneHistoricalPay
	45, // 1: webrpc.TokenInfo.token_type:type_name -> entity.TokenType
	2,  // 2: webrpc.SetDelegationRequest.token_infos:type_name -> webrpc.TokenInfo
	2,  // 3: webrpc.OpenPaymentChannelRequest.token_info:type_name -> webrpc.TokenInfo
	2,  // 4: webrpc.DepositOrWithdrawRequest.token_info:type_name -> webrpc.TokenInfo
	2,  // 5: webrpc.GetPeerFreeBalanceRequest.token_info:type_name -> webrpc.TokenInfo
	2,  // 6: webrpc.SendConditionalPaymentRequest.token_info:type_name -> webrpc.TokenInfo
	46, // 7: webrpc.SendConditionalPaymentRequest.transfer_logic_type:type_name -> entity.TransferFunctionType
	11, // 8: webrpc.SendConditionalPaymentRequest.conditions:type_name -> webrpc.Condition
	47, // 9: webrpc.SendConditionalPaymentRequest.note:type_name -> google.protobuf.Any
	2,  // 10: webrpc.SendTokenRequest.token_info:type_name -> webrpc.TokenInfo
	47, // 11: webrpc.SendTokenRequest.note:type_name -> google.protobuf.Any
	2,  // 12: webrpc.PaymentInfo.token_info:type_name -> webrpc.TokenInfo
	15, // 13: webrpc.OutgoingPaymentInfo.payment:type_name -> webrpc.PaymentInfo
	0,  // 14: webrpc.WebApi.GetPayHistory:input_type -> webrpc.GetPayHistoryRequest
	3,  // 15: webrpc.WebApi.SetDelegation:input_type -> webrpc.SetDelegationRequest
	4,  // 16: webrpc.WebApi.OpenPaymentChannel:input_type -> webrpc.OpenPaymentChannelRequest
	6,  // 17: webrpc.WebApi.Deposit:input_type -> webrpc.DepositOrWithdrawRequest
	6,  // 18: webrpc.WebApi.DepositNonBlocking:input_type -> webrpc.DepositOrWithdrawRequest
	7,  // 19: webrpc.WebApi.MonitorDepositJob:input_type -> webrpc.DepositOrWithdrawJob
	6,  // 20: webrpc.WebApi.CooperativeWithdraw:input_type -> webrpc.DepositOrWithdrawRequest
	6,  // 21: webrpc.WebApi.CooperativeWithdrawNonBlocking:input_type -> webrpc.DepositOrWithdrawRequest
	7,  // 22: webrpc.WebApi.MonitorCooperativeWithdrawJob:input_type -> webrpc.DepositOrWithdrawJob
	2,  // 23: webrpc.WebApi.GetBalance:input_type -> webrpc.TokenInfo
	9,  // 24: webrpc.WebApi.GetPeerFreeBalance:input_type -> webrpc.GetPeerFreeBalanceRequest
	13, // 25: webrpc.WebApi.SendToken:input_type -> webrpc.SendTokenRequest
	12, // 26: webrpc.WebApi.SendConditionalPayment:input_type -> webrpc.SendConditionalPaymentRequest
	48, // 27: webrpc.WebApi.SubscribeIncomingPayments:input_type -> google.protobuf.Empty
	48, // 28: webrpc.WebApi.SubscribeOutgoingPayments:input_type -> google.protobuf.Empty
	14, // 29: webrpc.WebApi.GetIncomingPaymentStatus:input_type -> webrpc.PaymentID
	14, // 30: webrpc.WebApi.GetOutgoingPaymentStatus:input_type -> webrpc.PaymentID
	14, // 31: webrpc.WebApi.ConfirmOutgoingPayment:input_type -> webrpc.PaymentID
	14, // 32: webrpc.WebApi.RejectIncomingPayment:input_type -> webrpc.PaymentID
	14, // 33: webrpc.WebApi.SettleOnChainResolvedIncomingPayment:input_type -> webrpc.PaymentID
	14, // 34: webrpc.WebApi.ResolveIncomingPaymentOnChain:input_type -> webrpc.PaymentID
	14, // 35: webrpc.WebApi.GetOnChainPaymentInfo:input_type -> webrpc.PaymentID
	2,  // 36: webrpc.WebApi.ConfirmOnChainResolvedPayments:input_type -> webrpc.TokenInfo
	2,  // 37: webrpc.WebApi.SettleExpiredPayments:input_type -> webrpc.TokenInfo
	6,  // 38: webrpc.WebApi.IntendWithdraw:input_type -> webrpc.DepositOrWithdrawRequest
	2,  // 39: webrpc.WebApi.ConfirmWithdraw:input_type -> webrpc.TokenInfo
	2,  // 40: webrpc.WebApi.IntendSettlePaymentChannel:input_type -> webrpc.TokenInfo
	2,  // 41: webrpc.WebApi.ConfirmSettlePaymentChannel:input_type -> webrpc.TokenInfo
	2,  // 42: webrpc.WebApi.GetSettleFinalizedTimeForPaymentChannel:input_type -> webrpc.TokenInfo
	2,  // 43: webrpc.WebApi.SyncOnChainPaymentChannelStatus:input_type -> webrpc.TokenInfo
	48, // 44: webrpc.WebApi.SyncStateWithPeer:input_type -> google.protobuf.Empty
	19, // 45: webrpc.WebApi.CreateAppSessionOnVirtualContract:input_type -> webrpc.CreateAppSessionOnVirtualContractRequest
	20, // 46: webrpc.WebApi.CreateAppSessionOnDeployedContract:input_type -> webrpc.CreateAppSessionOnDeployedContractRequest
	18, // 47: webrpc.WebApi.SubscribeAppSessionDispute:input_type -> webrpc.SessionID
	22, // 48: webrpc.WebApi.SignOutgoingState:input_type -> webrpc.SignOutgoingStateRequest
	26, // 49: webrpc.WebApi.ValidateAck:input_type -> webrpc.ValidateAckRequest
	24, // 50: webrpc.WebApi.SignData:input_type -> webrpc.Data
	28, // 51: webrpc.WebApi.ProcessReceivedState:input_type -> webrpc.ProcessReceivedStateRequest
	30, // 52: webrpc.WebApi.SettleAppSession:input_type -> webrpc.SettleAppSessionRequest
	31, // 53: webrpc.WebApi.SettleAppSessionBySigTimeout:input_type -> webrpc.SettleAppSessionByTimeoutRequest
	31, // 54: webrpc.WebApi.SettleAppSessionByMoveTimeout:input_type -> webrpc.SettleAppSessionByTimeoutRequest
	32, // 55: webrpc.WebApi.SettleAppSessionByInvalidTurn:input_type -> webrpc.SettleAppSessionByInvalidityRequest
	32, // 56: webrpc.WebApi.SettleAppSessionByInvalidState:input_type -> webrpc.SettleAppSessionByInvalidityRequest
	18, // 57: webrpc.WebApi.DeleteAppSession:input_type -> webrpc.SessionID
	18, // 58: webrpc.WebApi.GetDeployedAddressForAppSession:input_type -> webrpc.SessionID
	34, // 59: webrpc.WebApi.GetBooleanOutcomeForAppSession:input_type -> webrpc.GetBooleanOutcomeForAppSessionRequest
	36, // 60: webrpc.WebApi.ApplyActionForAppSession:input_type -> webrpc.ApplyActionForAppSessionRequest
	18, // 61: webrpc.WebApi.FinalizeOnActionTimeoutForAppSession:input_type -> webrpc.SessionID
	18, // 62: webrpc.WebApi.GetSettleFinalizedTimeForAppSession:input_type -> webrpc.SessionID
	18, // 63: webrpc.WebApi.GetActionDeadlineForAppSession:input_type -> webrpc.SessionID
	18, // 64: webrpc.WebApi.GetStatusForAppSession:input_type -> webrpc.SessionID
	39, // 65: webrpc.WebApi.GetStateForAppSession:input_type -> webrpc.GetStateForAppSessionRequest
	18, // 66: webrpc.WebApi.GetSeqNumForAppSession:input_type -> webrpc.SessionID
	48, // 67: webrpc.WebApi.GetBlockNumber:input_type -> google.protobuf.Empty
	42, // 68: webrpc.WebApi.SetMsgDropper:input_type -> webrpc.SetMsgDropReq
	1,  // 69: webrpc.WebApi.GetPayHistory:output_type -> webrpc.GetPayHistoryResponse
	48, // 70: webrpc.WebApi.SetDelegation:output_type -> google.protobuf.Empty
	5,  // 71: webrpc.WebApi.OpenPaymentChannel:output_type -> webrpc.ChannelID
	7,  // 72: webrpc.WebApi.Deposit:output_type -> webrpc.DepositOrWithdrawJob
	7,  // 73: webrpc.WebApi.DepositNonBlocking:output_type -> webrpc.DepositOrWithdrawJob
	7,  // 74: webrpc.WebApi.MonitorDepositJob:output_type -> webrpc.DepositOrWithdrawJob
	7,  // 75: webrpc.WebApi.CooperativeWithdraw:output_type -> webrpc.DepositOrWithdrawJob
	7,  // 76: webrpc.WebApi.CooperativeWithdrawNonBlocking:output_type -> webrpc.DepositOrWithdrawJob
	7,  // 77: webrpc.WebApi.MonitorCooperativeWithdrawJob:output_type -> webrpc.DepositOrWithdrawJob
	8,  // 78: webrpc.WebApi.GetBalance:output_type -> webrpc.GetBalanceResponse
	10, // 79: webrpc.WebApi.GetPeerFreeBalance:output_type -> webrpc.FreeBalance
	14, // 80: webrpc.WebApi.SendToken:output_type -> webrpc.PaymentID
	14, // 81: webrpc.WebApi.SendConditionalPayment:output_type -> webrpc.PaymentID
	15, // 82: webrpc.WebApi.SubscribeIncomingPayments:output_type -> webrpc.PaymentInfo
	16, // 83: webrpc.WebApi.SubscribeOutgoingPayments:output_type -> webrpc.OutgoingPaymentInfo
	43, // 84: webrpc.WebApi.GetIncomingPaymentStatus:output_type -> webrpc.PaymentStatus
	43, // 85: webrpc.WebApi.GetOutgoingPaymentStatus:output_type -> webrpc.PaymentStatus
	48, // 86: webrpc.WebApi.ConfirmOutgoingPayment:output_type -> google.protobuf.Empty
	48, // 87: webrpc.WebApi.RejectIncomingPayment:output_type -> google.protobuf.Empty
	48, // 88: webrpc.WebApi.SettleOnChainResolvedIncomingPayment:output_type -> google.protobuf.Empty
	48, // 89: webrpc.WebApi.ResolveIncomingPaymentOnChain:output_type -> google.protobuf.Empty
	17, // 90: webrpc.WebApi.GetOnChainPaymentInfo:output_type -> webrpc.OnChainPaymentInfo
	48, // 91: webrpc.WebApi.ConfirmOnChainResolvedPayments:output_type -> google.protobuf.Empty
	48, // 92: webrpc.WebApi.SettleExpiredPayments:output_type -> google.protobuf.Empty
	48, // 93: webrpc.WebApi.IntendWithdraw:output_type -> google.protobuf.Empty
	48, // 94: webrpc.WebApi.ConfirmWithdraw:output_type -> google.protobuf.Empty
	48, // 95: webrpc.WebApi.IntendSettlePaymentChannel:output_type -> google.protobuf.Empty
	48, // 96: webrpc.WebApi.ConfirmSettlePaymentChannel:output_type -> google.protobuf.Empty
	37, // 97: webrpc.WebApi.GetSettleFinalizedTimeForPaymentChannel:output_type -> webrpc.BlockNumber
	48, // 98: webrpc.WebApi.SyncOnChainPaymentChannelStatus:output_type -> google.protobuf.Empty
	48, // 99: webrpc.WebApi.SyncStateWithPeer:output_type -> google.protobuf.Empty
	18, // 100: webrpc.WebApi.CreateAppSessionOnVirtualContract:output_type -> webrpc.SessionID
	18, // 101: webrpc.WebApi.CreateAppSessionOnDeployedContract:output_type -> webrpc.SessionID
	21, // 102: webrpc.WebApi.SubscribeAppSessionDispute:output_type -> webrpc.DisputeInfo
	23, // 103: webrpc.WebApi.SignOutgoingState:output_type -> webrpc.SignedState
	27, // 104: webrpc.WebApi.ValidateAck:output_type -> webrpc.BoolValue
	25, // 105: webrpc.WebApi.SignData:output_type -> webrpc.Signature
	29, // 106: webrpc.WebApi.ProcessReceivedState:output_type -> webrpc.ProcessReceivedStateResponse
	48, // 107: webrpc.WebApi.SettleAppSession:output_type -> google.protobuf.Empty
	48, // 108: webrpc.WebApi.SettleAppSessionBySigTimeout:output_type -> google.protobuf.Empty
	48, // 109: webrpc.WebApi.SettleAppSessionByMoveTimeout:output_type -> google.protobuf.Empty
	48, // 110: webrpc.WebApi.SettleAppSessionByInvalidTurn:output_type -> google.protobuf.Empty
	48, // 111: webrpc.WebApi.SettleAppSessionByInvalidState:output_type -> google.protobuf.Empty
	48, // 112: webrpc.WebApi.DeleteAppSession:output_type -> google.protobuf.Empty
	33, // 113: webrpc.WebApi.GetDeployedAddressForAppSession:output_type -> webrpc.Address
	35, // 114: webrpc.WebApi.GetBooleanOutcomeForAppSession:output_type -> webrpc.BooleanOutcome
	48, // 115: webrpc.WebApi.ApplyActionForAppSession:output_type -> google.protobuf.Empty
	48, // 116: webrpc.WebApi.FinalizeOnActionTimeoutForAppSession:output_type -> google.protobuf.Empty
	37, // 117: webrpc.WebApi.GetSettleFinalizedTimeForAppSession:output_type -> webrpc.BlockNumber
	37, // 118: webrpc.WebApi.GetActionDeadlineForAppSession:output_type -> webrpc.BlockNumber
	38, // 119: webrpc.WebApi.GetStatusForAppSession:output_type -> webrpc.AppSessionStatus
	40, // 120: webrpc.WebApi.GetStateForAppSession:output_type -> webrpc.AppSessionState
	41, // 121: webrpc.WebApi.GetSeqNumForAppSession:output_type -> webrpc.AppSessionSeqNum
	37, // 122: webrpc.WebApi.GetBlockNumber:output_type -> webrpc.BlockNumber
	48, // 123: webrpc.WebApi.SetMsgDropper:output_type -> google.protobuf.Empty
	69, // [69:124] is the sub-list for method output_type
	14, // [14:69] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_web_api_proto_init() }
func file_web_api_proto_init() {
	if File_web_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_api_proto_rawDesc), len(file_web_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_api_proto_goTypes,
		DependencyIndexes: file_web_api_proto_depIdxs,
		MessageInfos:      file_web_api_proto_msgTypes,
	}.Build()
	File_web_api_proto = out.File
	file_web_api_proto_goTypes = nil
	file_web_api_proto_depIdxs = nil
}
