// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: fee.proto

package celerx_fee_interface

import (
	entity "github.com/celer-network/agent-pay/entity"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------------- OSP-facing service -----------------------------
// Next Tag: 2
type NewHopStreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewHopStreamEvent) Reset() {
	*x = NewHopStreamEvent{}
	mi := &file_fee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewHopStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewHopStreamEvent) ProtoMessage() {}

func (x *NewHopStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewHopStreamEvent.ProtoReflect.Descriptor instead.
func (*NewHopStreamEvent) Descriptor() ([]byte, []int) {
	return file_fee_proto_rawDescGZIP(), []int{0}
}

func (x *NewHopStreamEvent) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// FeeEvent to be renamed to PayEvent to be use-case neutral and to be moved to proto repo.
// This message is now the API osp published for pay event.
// Next Tag: 6
type FeeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pay   *entity.ConditionalPay `protobuf:"bytes,1,opt,name=pay,proto3" json:"pay,omitempty"`
	// Deprecated: Marked as deprecated in fee.proto.
	Note          *anypb.Any `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	SendSuccess   bool       `protobuf:"varint,3,opt,name=send_success,json=sendSuccess,proto3" json:"send_success,omitempty"`
	PayId         []byte     `protobuf:"bytes,4,opt,name=pay_id,json=payId,proto3" json:"pay_id,omitempty"`
	NotePbString  string     `protobuf:"bytes,5,opt,name=note_pb_string,json=notePbString,proto3" json:"note_pb_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeEvent) Reset() {
	*x = FeeEvent{}
	mi := &file_fee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeEvent) ProtoMessage() {}

func (x *FeeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeEvent.ProtoReflect.Descriptor instead.
func (*FeeEvent) Descriptor() ([]byte, []int) {
	return file_fee_proto_rawDescGZIP(), []int{1}
}

func (x *FeeEvent) GetPay() *entity.ConditionalPay {
	if x != nil {
		return x.Pay
	}
	return nil
}

// Deprecated: Marked as deprecated in fee.proto.
func (x *FeeEvent) GetNote() *anypb.Any {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *FeeEvent) GetSendSuccess() bool {
	if x != nil {
		return x.SendSuccess
	}
	return false
}

func (x *FeeEvent) GetPayId() []byte {
	if x != nil {
		return x.PayId
	}
	return nil
}

func (x *FeeEvent) GetNotePbString() string {
	if x != nil {
		return x.NotePbString
	}
	return ""
}

var File_fee_proto protoreflect.FileDescriptor

const file_fee_proto_rawDesc = "" +
	"\n" +
	"\tfee.proto\x12\x14celerx.fee.interface\x1a\fentity.proto\x1a\x19google/protobuf/any.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\x11NewHopStreamEvent\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\"\xc2\x01\n" +
	"\bFeeEvent\x12(\n" +
	"\x03pay\x18\x01 \x01(\v2\x16.entity.ConditionalPayR\x03pay\x12,\n" +
	"\x04note\x18\x02 \x01(\v2\x14.google.protobuf.AnyB\x02\x18\x01R\x04note\x12!\n" +
	"\fsend_success\x18\x03 \x01(\bR\vsendSuccess\x12\x15\n" +
	"\x06pay_id\x18\x04 \x01(\fR\x05payId\x12$\n" +
	"\x0enote_pb_string\x18\x05 \x01(\tR\fnotePbString2\xec\x02\n" +
	"\rOspSubscriber\x12t\n" +
	"\x0fNotifyNewStream\x12'.celerx.fee.interface.NewHopStreamEvent\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/notify/osp/newstream\x12o\n" +
	"\x11NotifyFeeReceived\x12\x1e.celerx.fee.interface.FeeEvent\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/notify/osp/feereceived\x12t\n" +
	"\x15NotifyFeeSendComplete\x12\x1e.celerx.fee.interface.FeeEvent\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/notify/osp/sendcompleteBOZMgithub.com/celer-network/agent-pay/fee-manager/interface;celerx_fee_interfaceb\x06proto3"

var (
	file_fee_proto_rawDescOnce sync.Once
	file_fee_proto_rawDescData []byte
)

func file_fee_proto_rawDescGZIP() []byte {
	file_fee_proto_rawDescOnce.Do(func() {
		file_fee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fee_proto_rawDesc), len(file_fee_proto_rawDesc)))
	})
	return file_fee_proto_rawDescData
}

var file_fee_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fee_proto_goTypes = []any{
	(*NewHopStreamEvent)(nil),     // 0: celerx.fee.interface.NewHopStreamEvent
	(*FeeEvent)(nil),              // 1: celerx.fee.interface.FeeEvent
	(*entity.ConditionalPay)(nil), // 2: entity.ConditionalPay
	(*anypb.Any)(nil),             // 3: google.protobuf.Any
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_fee_proto_depIdxs = []int32{
	2, // 0: celerx.fee.interface.FeeEvent.pay:type_name -> entity.ConditionalPay
	3, // 1: celerx.fee.interface.FeeEvent.note:type_name -> google.protobuf.Any
	0, // 2: celerx.fee.interface.OspSubscriber.NotifyNewStream:input_type -> celerx.fee.interface.NewHopStreamEvent
	1, // 3: celerx.fee.interface.OspSubscriber.NotifyFeeReceived:input_type -> celerx.fee.interface.FeeEvent
	1, // 4: celerx.fee.interface.OspSubscriber.NotifyFeeSendComplete:input_type -> celerx.fee.interface.FeeEvent
	4, // 5: celerx.fee.interface.OspSubscriber.NotifyNewStream:output_type -> google.protobuf.Empty
	4, // 6: celerx.fee.interface.OspSubscriber.NotifyFeeReceived:output_type -> google.protobuf.Empty
	4, // 7: celerx.fee.interface.OspSubscriber.NotifyFeeSendComplete:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fee_proto_init() }
func file_fee_proto_init() {
	if File_fee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fee_proto_rawDesc), len(file_fee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fee_proto_goTypes,
		DependencyIndexes: file_fee_proto_depIdxs,
		MessageInfos:      file_fee_proto_msgTypes,
	}.Build()
	File_fee_proto = out.File
	file_fee_proto_goTypes = nil
	file_fee_proto_depIdxs = nil
}
