// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package celerx_fee_interface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// OspSubscriberClient is the client API for OspSubscriber service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OspSubscriberClient interface {
	NotifyNewStream(ctx context.Context, in *NewHopStreamEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NotifyFeeReceived(ctx context.Context, in *FeeEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	NotifyFeeSendComplete(ctx context.Context, in *FeeEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type ospSubscriberClient struct {
	cc grpc.ClientConnInterface
}

func NewOspSubscriberClient(cc grpc.ClientConnInterface) OspSubscriberClient {
	return &ospSubscriberClient{cc}
}

func (c *ospSubscriberClient) NotifyNewStream(ctx context.Context, in *NewHopStreamEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/celerx.fee.interface.OspSubscriber/NotifyNewStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ospSubscriberClient) NotifyFeeReceived(ctx context.Context, in *FeeEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/celerx.fee.interface.OspSubscriber/NotifyFeeReceived", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ospSubscriberClient) NotifyFeeSendComplete(ctx context.Context, in *FeeEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/celerx.fee.interface.OspSubscriber/NotifyFeeSendComplete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OspSubscriberServer is the server API for OspSubscriber service.
// All implementations should embed UnimplementedOspSubscriberServer
// for forward compatibility
type OspSubscriberServer interface {
	NotifyNewStream(context.Context, *NewHopStreamEvent) (*emptypb.Empty, error)
	NotifyFeeReceived(context.Context, *FeeEvent) (*emptypb.Empty, error)
	NotifyFeeSendComplete(context.Context, *FeeEvent) (*emptypb.Empty, error)
}

// UnimplementedOspSubscriberServer should be embedded to have forward compatible implementations.
type UnimplementedOspSubscriberServer struct {
}

func (UnimplementedOspSubscriberServer) NotifyNewStream(context.Context, *NewHopStreamEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyNewStream not implemented")
}
func (UnimplementedOspSubscriberServer) NotifyFeeReceived(context.Context, *FeeEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyFeeReceived not implemented")
}
func (UnimplementedOspSubscriberServer) NotifyFeeSendComplete(context.Context, *FeeEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyFeeSendComplete not implemented")
}

// UnsafeOspSubscriberServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OspSubscriberServer will
// result in compilation errors.
type UnsafeOspSubscriberServer interface {
	mustEmbedUnimplementedOspSubscriberServer()
}

func RegisterOspSubscriberServer(s *grpc.Server, srv OspSubscriberServer) {
	s.RegisterService(&_OspSubscriber_serviceDesc, srv)
}

func _OspSubscriber_NotifyNewStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewHopStreamEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OspSubscriberServer).NotifyNewStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celerx.fee.interface.OspSubscriber/NotifyNewStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OspSubscriberServer).NotifyNewStream(ctx, req.(*NewHopStreamEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _OspSubscriber_NotifyFeeReceived_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OspSubscriberServer).NotifyFeeReceived(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celerx.fee.interface.OspSubscriber/NotifyFeeReceived",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OspSubscriberServer).NotifyFeeReceived(ctx, req.(*FeeEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _OspSubscriber_NotifyFeeSendComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeeEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OspSubscriberServer).NotifyFeeSendComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celerx.fee.interface.OspSubscriber/NotifyFeeSendComplete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OspSubscriberServer).NotifyFeeSendComplete(ctx, req.(*FeeEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var _OspSubscriber_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celerx.fee.interface.OspSubscriber",
	HandlerType: (*OspSubscriberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyNewStream",
			Handler:    _OspSubscriber_NotifyNewStream_Handler,
		},
		{
			MethodName: "NotifyFeeReceived",
			Handler:    _OspSubscriber_NotifyFeeReceived_Handler,
		},
		{
			MethodName: "NotifyFeeSendComplete",
			Handler:    _OspSubscriber_NotifyFeeSendComplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fee.proto",
}
