// Copyright 2018-2025 Celer Network

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: osp_report.proto

package ospreport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OSP voluntarily periodically send OspReport to the Celer Explorer server
type OspReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// serialized OspInfo
	OspInfo []byte `protobuf:"bytes,1,opt,name=osp_info,json=ospInfo,proto3" json:"osp_info,omitempty"`
	// signature of osp_info, signed by OSP eth address
	Sig           []byte `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OspReport) Reset() {
	*x = OspReport{}
	mi := &file_osp_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspReport) ProtoMessage() {}

func (x *OspReport) ProtoReflect() protoreflect.Message {
	mi := &file_osp_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspReport.ProtoReflect.Descriptor instead.
func (*OspReport) Descriptor() ([]byte, []int) {
	return file_osp_report_proto_rawDescGZIP(), []int{0}
}

func (x *OspReport) GetOspInfo() []byte {
	if x != nil {
		return x.OspInfo
	}
	return nil
}

func (x *OspReport) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type OspInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OSP eth address
	EthAddr string `protobuf:"bytes,1,opt,name=eth_addr,json=ethAddr,proto3" json:"eth_addr,omitempty"`
	// UTC unix timestamp in second
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// server public rpc host:port
	RpcHost  string          `protobuf:"bytes,3,opt,name=rpc_host,json=rpcHost,proto3" json:"rpc_host,omitempty"`
	OspPeers []*PeerBalances `protobuf:"bytes,4,rep,name=osp_peers,json=ospPeers,proto3" json:"osp_peers,omitempty"`
	// number of payments processed
	Payments int64 `protobuf:"varint,5,opt,name=payments,proto3" json:"payments,omitempty"`
	// accept anyone to connect
	OpenAccept bool `protobuf:"varint,6,opt,name=open_accept,json=openAccept,proto3" json:"open_accept,omitempty"`
	// standard open channel configuration
	StdOpenchanConfigs []*StdOpenChanConfig `protobuf:"bytes,7,rep,name=std_openchan_configs,json=stdOpenchanConfigs,proto3" json:"std_openchan_configs,omitempty"`
	AdminInfo          *AdminInfo           `protobuf:"bytes,8,opt,name=admin_info,json=adminInfo,proto3" json:"admin_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OspInfo) Reset() {
	*x = OspInfo{}
	mi := &file_osp_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OspInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OspInfo) ProtoMessage() {}

func (x *OspInfo) ProtoReflect() protoreflect.Message {
	mi := &file_osp_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OspInfo.ProtoReflect.Descriptor instead.
func (*OspInfo) Descriptor() ([]byte, []int) {
	return file_osp_report_proto_rawDescGZIP(), []int{1}
}

func (x *OspInfo) GetEthAddr() string {
	if x != nil {
		return x.EthAddr
	}
	return ""
}

func (x *OspInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OspInfo) GetRpcHost() string {
	if x != nil {
		return x.RpcHost
	}
	return ""
}

func (x *OspInfo) GetOspPeers() []*PeerBalances {
	if x != nil {
		return x.OspPeers
	}
	return nil
}

func (x *OspInfo) GetPayments() int64 {
	if x != nil {
		return x.Payments
	}
	return 0
}

func (x *OspInfo) GetOpenAccept() bool {
	if x != nil {
		return x.OpenAccept
	}
	return false
}

func (x *OspInfo) GetStdOpenchanConfigs() []*StdOpenChanConfig {
	if x != nil {
		return x.StdOpenchanConfigs
	}
	return nil
}

func (x *OspInfo) GetAdminInfo() *AdminInfo {
	if x != nil {
		return x.AdminInfo
	}
	return nil
}

type PeerBalances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Balances      []*ChannelBalance      `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerBalances) Reset() {
	*x = PeerBalances{}
	mi := &file_osp_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerBalances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerBalances) ProtoMessage() {}

func (x *PeerBalances) ProtoReflect() protoreflect.Message {
	mi := &file_osp_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerBalances.ProtoReflect.Descriptor instead.
func (*PeerBalances) Descriptor() ([]byte, []int) {
	return file_osp_report_proto_rawDescGZIP(), []int{2}
}

func (x *PeerBalances) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *PeerBalances) GetBalances() []*ChannelBalance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type ChannelBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	TokenAddr     string                 `protobuf:"bytes,2,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	SelfBalance   string                 `protobuf:"bytes,3,opt,name=self_balance,json=selfBalance,proto3" json:"self_balance,omitempty"`
	PeerBalance   string                 `protobuf:"bytes,4,opt,name=peer_balance,json=peerBalance,proto3" json:"peer_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelBalance) Reset() {
	*x = ChannelBalance{}
	mi := &file_osp_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelBalance) ProtoMessage() {}

func (x *ChannelBalance) ProtoReflect() protoreflect.Message {
	mi := &file_osp_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelBalance.ProtoReflect.Descriptor instead.
func (*ChannelBalance) Descriptor() ([]byte, []int) {
	return file_osp_report_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelBalance) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *ChannelBalance) GetTokenAddr() string {
	if x != nil {
		return x.TokenAddr
	}
	return ""
}

func (x *ChannelBalance) GetSelfBalance() string {
	if x != nil {
		return x.SelfBalance
	}
	return ""
}

func (x *ChannelBalance) GetPeerBalance() string {
	if x != nil {
		return x.PeerBalance
	}
	return ""
}

// standard open channel config
type StdOpenChanConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenAddr     string                 `protobuf:"bytes,1,opt,name=token_addr,json=tokenAddr,proto3" json:"token_addr,omitempty"`
	MinDeposit    string                 `protobuf:"bytes,2,opt,name=min_deposit,json=minDeposit,proto3" json:"min_deposit,omitempty"`
	MaxDeposit    string                 `protobuf:"bytes,3,opt,name=max_deposit,json=maxDeposit,proto3" json:"max_deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdOpenChanConfig) Reset() {
	*x = StdOpenChanConfig{}
	mi := &file_osp_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdOpenChanConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdOpenChanConfig) ProtoMessage() {}

func (x *StdOpenChanConfig) ProtoReflect() protoreflect.Message {
	mi := &file_osp_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdOpenChanConfig.ProtoReflect.Descriptor instead.
func (*StdOpenChanConfig) Descriptor() ([]byte, []int) {
	return file_osp_report_proto_rawDescGZIP(), []int{4}
}

func (x *StdOpenChanConfig) GetTokenAddr() string {
	if x != nil {
		return x.TokenAddr
	}
	return ""
}

func (x *StdOpenChanConfig) GetMinDeposit() string {
	if x != nil {
		return x.MinDeposit
	}
	return ""
}

func (x *StdOpenChanConfig) GetMaxDeposit() string {
	if x != nil {
		return x.MaxDeposit
	}
	return ""
}

type AdminInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Organization  string                 `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Website       string                 `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminInfo) Reset() {
	*x = AdminInfo{}
	mi := &file_osp_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminInfo) ProtoMessage() {}

func (x *AdminInfo) ProtoReflect() protoreflect.Message {
	mi := &file_osp_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminInfo.ProtoReflect.Descriptor instead.
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return file_osp_report_proto_rawDescGZIP(), []int{5}
}

func (x *AdminInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AdminInfo) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *AdminInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AdminInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

var File_osp_report_proto protoreflect.FileDescriptor

const file_osp_report_proto_rawDesc = "" +
	"\n" +
	"\x10osp_report.proto\x12\tospreport\"8\n" +
	"\tOspReport\x12\x19\n" +
	"\bosp_info\x18\x01 \x01(\fR\aospInfo\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sig\"\xd5\x02\n" +
	"\aOspInfo\x12\x19\n" +
	"\beth_addr\x18\x01 \x01(\tR\aethAddr\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x19\n" +
	"\brpc_host\x18\x03 \x01(\tR\arpcHost\x124\n" +
	"\tosp_peers\x18\x04 \x03(\v2\x17.ospreport.PeerBalancesR\bospPeers\x12\x1a\n" +
	"\bpayments\x18\x05 \x01(\x03R\bpayments\x12\x1f\n" +
	"\vopen_accept\x18\x06 \x01(\bR\n" +
	"openAccept\x12N\n" +
	"\x14std_openchan_configs\x18\a \x03(\v2\x1c.ospreport.StdOpenChanConfigR\x12stdOpenchanConfigs\x123\n" +
	"\n" +
	"admin_info\x18\b \x01(\v2\x14.ospreport.AdminInfoR\tadminInfo\"Y\n" +
	"\fPeerBalances\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\x125\n" +
	"\bbalances\x18\x02 \x03(\v2\x19.ospreport.ChannelBalanceR\bbalances\"\x87\x01\n" +
	"\x0eChannelBalance\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x1d\n" +
	"\n" +
	"token_addr\x18\x02 \x01(\tR\ttokenAddr\x12!\n" +
	"\fself_balance\x18\x03 \x01(\tR\vselfBalance\x12!\n" +
	"\fpeer_balance\x18\x04 \x01(\tR\vpeerBalance\"t\n" +
	"\x11StdOpenChanConfig\x12\x1d\n" +
	"\n" +
	"token_addr\x18\x01 \x01(\tR\ttokenAddr\x12\x1f\n" +
	"\vmin_deposit\x18\x02 \x01(\tR\n" +
	"minDeposit\x12\x1f\n" +
	"\vmax_deposit\x18\x03 \x01(\tR\n" +
	"maxDeposit\"\x8d\x01\n" +
	"\tAdminInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\"\n" +
	"\forganization\x18\x03 \x01(\tR\forganization\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsiteB4Z2github.com/celer-network/agent-pay/route/ospreportb\x06proto3"

var (
	file_osp_report_proto_rawDescOnce sync.Once
	file_osp_report_proto_rawDescData []byte
)

func file_osp_report_proto_rawDescGZIP() []byte {
	file_osp_report_proto_rawDescOnce.Do(func() {
		file_osp_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_osp_report_proto_rawDesc), len(file_osp_report_proto_rawDesc)))
	})
	return file_osp_report_proto_rawDescData
}

var file_osp_report_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_osp_report_proto_goTypes = []any{
	(*OspReport)(nil),         // 0: ospreport.OspReport
	(*OspInfo)(nil),           // 1: ospreport.OspInfo
	(*PeerBalances)(nil),      // 2: ospreport.PeerBalances
	(*ChannelBalance)(nil),    // 3: ospreport.ChannelBalance
	(*StdOpenChanConfig)(nil), // 4: ospreport.StdOpenChanConfig
	(*AdminInfo)(nil),         // 5: ospreport.AdminInfo
}
var file_osp_report_proto_depIdxs = []int32{
	2, // 0: ospreport.OspInfo.osp_peers:type_name -> ospreport.PeerBalances
	4, // 1: ospreport.OspInfo.std_openchan_configs:type_name -> ospreport.StdOpenChanConfig
	5, // 2: ospreport.OspInfo.admin_info:type_name -> ospreport.AdminInfo
	3, // 3: ospreport.PeerBalances.balances:type_name -> ospreport.ChannelBalance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_osp_report_proto_init() }
func file_osp_report_proto_init() {
	if File_osp_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_osp_report_proto_rawDesc), len(file_osp_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_osp_report_proto_goTypes,
		DependencyIndexes: file_osp_report_proto_depIdxs,
		MessageInfos:      file_osp_report_proto_msgTypes,
	}.Build()
	File_osp_report_proto = out.File
	file_osp_report_proto_goTypes = nil
	file_osp_report_proto_depIdxs = nil
}
