// Copyright 2019-2025 Celer Network

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: web_proxy.proto

package rpc

import (
	rpc "github.com/celer-network/agent-pay/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionToken) Reset() {
	*x = SessionToken{}
	mi := &file_web_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionToken) ProtoMessage() {}

func (x *SessionToken) ProtoReflect() protoreflect.Message {
	mi := &file_web_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionToken.ProtoReflect.Descriptor instead.
func (*SessionToken) Descriptor() ([]byte, []int) {
	return file_web_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *SessionToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_web_proxy_proto protoreflect.FileDescriptor

const file_web_proxy_proto_rawDesc = "" +
	"\n" +
	"\x0fweb_proxy.proto\x12\vwebproxyrpc\x1a\x1bgoogle/protobuf/empty.proto\x1a\rmessage.proto\"$\n" +
	"\fSessionToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\x85\x02\n" +
	"\vWebProxyRpc\x12D\n" +
	"\rCreateSession\x12\x16.google.protobuf.Empty\x1a\x19.webproxyrpc.SessionToken\"\x00\x12B\n" +
	"\vOpenChannel\x12\x17.rpc.OpenChannelRequest\x1a\x18.rpc.OpenChannelResponse\"\x00\x124\n" +
	"\x11SubscribeMessages\x12\f.rpc.AuthReq\x1a\r.rpc.CelerMsg\"\x000\x01\x126\n" +
	"\vSendMessage\x12\r.rpc.CelerMsg\x1a\x16.google.protobuf.Empty\"\x00B1Z/github.com/celer-network/agent-pay/webproxy/rpcb\x06proto3"

var (
	file_web_proxy_proto_rawDescOnce sync.Once
	file_web_proxy_proto_rawDescData []byte
)

func file_web_proxy_proto_rawDescGZIP() []byte {
	file_web_proxy_proto_rawDescOnce.Do(func() {
		file_web_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_web_proxy_proto_rawDesc), len(file_web_proxy_proto_rawDesc)))
	})
	return file_web_proxy_proto_rawDescData
}

var file_web_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_web_proxy_proto_goTypes = []any{
	(*SessionToken)(nil),            // 0: webproxyrpc.SessionToken
	(*emptypb.Empty)(nil),           // 1: google.protobuf.Empty
	(*rpc.OpenChannelRequest)(nil),  // 2: rpc.OpenChannelRequest
	(*rpc.AuthReq)(nil),             // 3: rpc.AuthReq
	(*rpc.CelerMsg)(nil),            // 4: rpc.CelerMsg
	(*rpc.OpenChannelResponse)(nil), // 5: rpc.OpenChannelResponse
}
var file_web_proxy_proto_depIdxs = []int32{
	1, // 0: webproxyrpc.WebProxyRpc.CreateSession:input_type -> google.protobuf.Empty
	2, // 1: webproxyrpc.WebProxyRpc.OpenChannel:input_type -> rpc.OpenChannelRequest
	3, // 2: webproxyrpc.WebProxyRpc.SubscribeMessages:input_type -> rpc.AuthReq
	4, // 3: webproxyrpc.WebProxyRpc.SendMessage:input_type -> rpc.CelerMsg
	0, // 4: webproxyrpc.WebProxyRpc.CreateSession:output_type -> webproxyrpc.SessionToken
	5, // 5: webproxyrpc.WebProxyRpc.OpenChannel:output_type -> rpc.OpenChannelResponse
	4, // 6: webproxyrpc.WebProxyRpc.SubscribeMessages:output_type -> rpc.CelerMsg
	1, // 7: webproxyrpc.WebProxyRpc.SendMessage:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_web_proxy_proto_init() }
func file_web_proxy_proto_init() {
	if File_web_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_proxy_proto_rawDesc), len(file_web_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_web_proxy_proto_goTypes,
		DependencyIndexes: file_web_proxy_proto_depIdxs,
		MessageInfos:      file_web_proxy_proto_msgTypes,
	}.Build()
	File_web_proxy_proto = out.File
	file_web_proxy_proto_goTypes = nil
	file_web_proxy_proto_depIdxs = nil
}
