// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	rpc "github.com/celer-network/agent-pay/rpc"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// WebProxyRpcClient is the client API for WebProxyRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebProxyRpcClient interface {
	CreateSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SessionToken, error)
	OpenChannel(ctx context.Context, in *rpc.OpenChannelRequest, opts ...grpc.CallOption) (*rpc.OpenChannelResponse, error)
	SubscribeMessages(ctx context.Context, in *rpc.AuthReq, opts ...grpc.CallOption) (WebProxyRpc_SubscribeMessagesClient, error)
	SendMessage(ctx context.Context, in *rpc.CelerMsg, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type webProxyRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewWebProxyRpcClient(cc grpc.ClientConnInterface) WebProxyRpcClient {
	return &webProxyRpcClient{cc}
}

func (c *webProxyRpcClient) CreateSession(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SessionToken, error) {
	out := new(SessionToken)
	err := c.cc.Invoke(ctx, "/webproxyrpc.WebProxyRpc/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webProxyRpcClient) OpenChannel(ctx context.Context, in *rpc.OpenChannelRequest, opts ...grpc.CallOption) (*rpc.OpenChannelResponse, error) {
	out := new(rpc.OpenChannelResponse)
	err := c.cc.Invoke(ctx, "/webproxyrpc.WebProxyRpc/OpenChannel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webProxyRpcClient) SubscribeMessages(ctx context.Context, in *rpc.AuthReq, opts ...grpc.CallOption) (WebProxyRpc_SubscribeMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WebProxyRpc_serviceDesc.Streams[0], "/webproxyrpc.WebProxyRpc/SubscribeMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &webProxyRpcSubscribeMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WebProxyRpc_SubscribeMessagesClient interface {
	Recv() (*rpc.CelerMsg, error)
	grpc.ClientStream
}

type webProxyRpcSubscribeMessagesClient struct {
	grpc.ClientStream
}

func (x *webProxyRpcSubscribeMessagesClient) Recv() (*rpc.CelerMsg, error) {
	m := new(rpc.CelerMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *webProxyRpcClient) SendMessage(ctx context.Context, in *rpc.CelerMsg, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/webproxyrpc.WebProxyRpc/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebProxyRpcServer is the server API for WebProxyRpc service.
// All implementations should embed UnimplementedWebProxyRpcServer
// for forward compatibility
type WebProxyRpcServer interface {
	CreateSession(context.Context, *emptypb.Empty) (*SessionToken, error)
	OpenChannel(context.Context, *rpc.OpenChannelRequest) (*rpc.OpenChannelResponse, error)
	SubscribeMessages(*rpc.AuthReq, WebProxyRpc_SubscribeMessagesServer) error
	SendMessage(context.Context, *rpc.CelerMsg) (*emptypb.Empty, error)
}

// UnimplementedWebProxyRpcServer should be embedded to have forward compatible implementations.
type UnimplementedWebProxyRpcServer struct {
}

func (UnimplementedWebProxyRpcServer) CreateSession(context.Context, *emptypb.Empty) (*SessionToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedWebProxyRpcServer) OpenChannel(context.Context, *rpc.OpenChannelRequest) (*rpc.OpenChannelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenChannel not implemented")
}
func (UnimplementedWebProxyRpcServer) SubscribeMessages(*rpc.AuthReq, WebProxyRpc_SubscribeMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMessages not implemented")
}
func (UnimplementedWebProxyRpcServer) SendMessage(context.Context, *rpc.CelerMsg) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

// UnsafeWebProxyRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebProxyRpcServer will
// result in compilation errors.
type UnsafeWebProxyRpcServer interface {
	mustEmbedUnimplementedWebProxyRpcServer()
}

func RegisterWebProxyRpcServer(s *grpc.Server, srv WebProxyRpcServer) {
	s.RegisterService(&_WebProxyRpc_serviceDesc, srv)
}

func _WebProxyRpc_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebProxyRpcServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webproxyrpc.WebProxyRpc/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebProxyRpcServer).CreateSession(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebProxyRpc_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rpc.OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebProxyRpcServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webproxyrpc.WebProxyRpc/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebProxyRpcServer).OpenChannel(ctx, req.(*rpc.OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebProxyRpc_SubscribeMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(rpc.AuthReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WebProxyRpcServer).SubscribeMessages(m, &webProxyRpcSubscribeMessagesServer{stream})
}

type WebProxyRpc_SubscribeMessagesServer interface {
	Send(*rpc.CelerMsg) error
	grpc.ServerStream
}

type webProxyRpcSubscribeMessagesServer struct {
	grpc.ServerStream
}

func (x *webProxyRpcSubscribeMessagesServer) Send(m *rpc.CelerMsg) error {
	return x.ServerStream.SendMsg(m)
}

func _WebProxyRpc_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(rpc.CelerMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebProxyRpcServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webproxyrpc.WebProxyRpc/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebProxyRpcServer).SendMessage(ctx, req.(*rpc.CelerMsg))
	}
	return interceptor(ctx, in, info, handler)
}

var _WebProxyRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webproxyrpc.WebProxyRpc",
	HandlerType: (*WebProxyRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _WebProxyRpc_CreateSession_Handler,
		},
		{
			MethodName: "OpenChannel",
			Handler:    _WebProxyRpc_OpenChannel_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _WebProxyRpc_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMessages",
			Handler:       _WebProxyRpc_SubscribeMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "web_proxy.proto",
}
